apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lanparty-seating
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: "traefik.k8s.235.tdude.co"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - seating.tdude.co
    secretName: seating-tdude-co-tls
  rules:
  - host: seating.tdude.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lanparty-seating
            port:
              name: http