apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secrets
    labels:
        app.kubernetes.io/name: minecraft-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:D/NuYZe3MclKE1Szim+VfnX4QYwoh2YNgzLMkjNgbEs=,iv:O4XL+3KDKlKTJsgf+Ixr5SupUydU0t2p8E9xZKw6yOY=,tag:cS8uSn/WVFB3EkGEFgX/Gg==,type:str]
    WHITELIST: ENC[AES256_GCM,data:vZMzAbl2xdVByhuxdgBgCo1EkQFqZDx/xPDWcGAVuCrMf96FGv7a+lD+QgTWwAPVZOvZBON274pJ+94YGKqWGxTu2uI/AkyCcV99GfPfaFMo7jur/FjbWgNUeQWk/homXksebvX+5vpiwbTk6XMr/0hOB+9S2Rzocw==,iv:TTJTMJ/DcRkFMQ3htQ/1N2u1wruWkcXorZtgOBKw7AY=,tag:TpncmybKZn7qq4NXxZu8LQ==,type:str]
    OPS: ENC[AES256_GCM,data:6vOJY5KZDrC3kw==,iv:z6E/6Wf3GOTYIao3LNCr9vrfJNQPdDJtIVx4/ot7jzQ=,tag:h1fZTIeipIxUYZbjQBISGw==,type:str]
    SEED: ""
sops:
    lastmodified: "2026-01-29T21:35:49Z"
    mac: ENC[AES256_GCM,data:1n6LpBWoaxmp+UbdDGpLC5Q55J/40yc2P+gGrVZzGTbfK2qjR1kePHvS6DjxNlv928NiTpRz+LDtGZIDvIy3hmRYJQhH70LEcf4EXMMiGt6ynxikPxrouDlT0c1I7zsPXKbBekyv+OlVdrQwxSNxrwIbT4Fl75AxMRPjCOJN/9o=,iv:UL5QTIxUxXve2ne/wg9nfiIjlipB5IaGOaIQMjgI8lM=,tag:5xnFC7XHBkddasF3qpYIfw==,type:str]
    pgp:
        - created_at: "2021-03-15T00:36:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ/+LEJ+vkI7cGGcnAqJMBQY0lnbQW6BQoBBSu0FlYgDSWVi
            XviCaqSdRs2ZwgexmJYlI9lPFTbH9r5yvvY6X+wlK3en5hvvXk764K6UlkPg8BYN
            t9qc72ZI6mn9bVjAoFm+41Z58CLJuef5kiEYquHLbtwhwtTPdROlvAGTQER5qTrb
            QytCfxTMIo++Ft9TC3GWG8xZvbEAH4YT7kG1pZgxtK0e4LiQiscnY1Tqal2TF4So
            rb12Pn+Ss9VGZRkDDkn8FIU+2JUC7157lJ+mw7cj7KOQVtvvm3UsNetItpl7lkzZ
            aNbdVQicj85KpKRT++RLVzBmFPeDWfLZYl6mP9prTDvZwH1FPCGXOKvkhJR9PzE3
            OvjdjcI3AbTF1iLnIsc+IYUGvA5TBv8a9U8AySSFDq0DJMDVuYzqxcJGpT/+n6kH
            EgWugl42LvAKSxP3QAetAdmojHW4flHsDRtCsvk5snTpeEUzUDeZcBnEpM0P1Ex4
            oMb1WIS/iWEeZKQQ1otuhv3VhK4onMIpfDTrYj/djaoWcqPVrK85CKY8PMyLlONq
            FxHx39t6VuE9XMO7py4GkthXd/1jxQbXGDylCFXkqFPksQVnXoIce+jydSu3BoFA
            Ec36TVsKAcnzp95/3YnupfX+tabO5pKNkh3boLMwvQc7VNNSu00ZonhgPYfbBXzS
            XgGYUadTEn9pmXlr8gKoI4RCppgQgIU+vMEmWW3adkQJA9+uPLbpTstoJ4uDQfaZ
            /PX7lz1jnqiJM9cGXPHgmWwszDTCyXwZYRn42PYfEQsg7YJouK/UOva17wPY/wI=
            =TLMG
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:36:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9ARAAha5H29ZNAM4Du8aL5kNg2yre4dQlmP8QMTaw39P2Fswh
            iIBPZuVrx1Vok+3kh5O84lMB/TVFBdhR/AdURH6wzzRe9cxggnDG8cXuukjQKf3C
            Ix2cjLu9KxWrBpqNuWFK8rm6cQwF92OgAPbE7yt7QNL0fp27TyWw2Xs05oziISD8
            9rdCxsRgRu3ecEyXsFQV3GSYLAMqzfFBNoBpUatGWPbjROscWXT8Jab/bLamYzDd
            b8FgH9/vmpx1cT34XUSHG6ESIMcXn0pRm+vqtlOEL57RN/yI7WrOQuSozaxKH2j1
            c/cXIwjFQGHB6FH0XdoCXRZrcG2j8969z/Xe55aATxb1EP6wcgEsSOouraQxQCVF
            QZQsUxk77yihVDEtM8SC2eaUkhW/qcS3OA9YUJj3IPK0/mI8cFeiu990SdZOyQnT
            yjWQqLV4mrkTooswB7Mjzt1hcDXuG6kbV+DhKDVkLLSDKkMe/yq+wsz8CuipLqNR
            nCtfFdQpJctT4UdL2xrT9+J7vGE4LlIYmWXXhIXVy43mnW1p69U8TeX0UdsT3lMY
            Mz0fThobBRR/wYQaoQgJEUwhEHppOaG8H6Wiyfy2eBUcQgbTjME5kXVFb0q9htIB
            vrJQlsTR8WoJ2aS8SROQEsy86aWohbqm5jnYUhXDXuD/dbTpZu74FZy6sRPpo5jS
            XgFnePQmCo22dDOGXleWLB7YvpkiFJ1ZSX/9v+NL8aIsxGJhzPolLu6jwjqeH/nw
            iSSXpm5UTYfl10BxbHSUK9IpxjULRWEsUqBxd3ZIyo1zBC8OSEijJPuKWcOG/ZQ=
            =+Gsr
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
