apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/namespace.yaml
# Snapshot stuff
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/csi-snapshotter?ref=v8.4.0
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.4.0
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/e6e14c16019ece315f91e8389b08cfcbd07d2e49/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/e6e14c16019ece315f91e8389b08cfcbd07d2e49/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/e6e14c16019ece315f91e8389b08cfcbd07d2e49/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
helmCharts:
- name: democratic-csi
  # includeCRDs: true
  releaseName: zfs-nfs
  version: 0.15.0
  repo: https://democratic-csi.github.io/charts/
  namespace: democratic-csi
  valuesFile: ./resources/values-nfs.yaml
- name: democratic-csi
  # includeCRDs: true
  releaseName: zfs-nfs-spitfire-fast
  version: 0.15.0
  repo: https://democratic-csi.github.io/charts/
  namespace: democratic-csi
  valuesFile: ./resources/values-nfs-spitfire-fast.yaml
- name: democratic-csi
  # includeCRDs: true
  releaseName: zfs-iscsi
  version: 0.15.0
  repo: https://democratic-csi.github.io/charts/
  namespace: democratic-csi
  valuesFile: ./resources/values-iscsi.yaml
