apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  labels:
    app.kubernetes.io/name: overseerr
spec:
  storageClassName: truenas-iscsi-spitfire-fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
