apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/deployment.yaml
- ./resources/service.yaml
- ./resources/namespace.yaml
- ./resources/postgres.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: lanparty-seating