apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpRENDQW5DZ0F3SUJBZ0lRYm42T0JpWHJ6NmRZSk8zRkU0RWtQekFOQmdrcWhraUc5dzBCQVFzRkFEQmUKTVE4d0RRWURWUVFEREFaTE9ITWdRMEV4Q3pBSkJnTlZCQVlUQWxWVE1ROHdEUVlEVlFRSERBWkJkWE4wYVc0eApEekFOQmdOVkJBb01Cazl5WVdOc1pURU1NQW9HQTFVRUN3d0RUMk5wTVE0d0RBWURWUVFJREFWVVpYaGhjekFlCkZ3MHlOakF5TVRnd05EVXpOREphRncwek1UQXlNVGd3TkRVek5ESmFNRjR4RHpBTkJnTlZCQU1NQmtzNGN5QkQKUVRFTE1Ba0dBMVVFQmhNQ1ZWTXhEekFOQmdOVkJBY01Ca0YxYzNScGJqRVBNQTBHQTFVRUNnd0dUM0poWTJ4bApNUXd3Q2dZRFZRUUxEQU5QWTJreERqQU1CZ05WQkFnTUJWUmxlR0Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBbXVNcHdzakY3UXdvdWFFWkQ0ZnJ5a045L2lCaG93N0NJclMzSUo3bXRTRFEKVUtINGhCdXI2VVE4R0J2V28rRWxCaDdjY040TVcyZFZnZ0dwMi9XeGpPUkU5Nm1GVUdjT0ZaUENiMEJab21pQQpsaGt3L3pVUEN1TWpaRmkvclRsbVlpZTB2U3ZsdEJFblo5Q2tNek1iNnc2T2lqbExONWFxK2hNdk04VWkwbGtyClR2LzFIaDlhc0NzMTQrMEkxeDRUUzNPNjZoYzdvZ3ZKWGladlBPdzN5V2psemFWWGx2YTlLb3dmY3I3dlczRHkKVWRjUEVMTVNqNFozc3lCWHhieXJDMEw5bDF6OUhLWGJDOWJ4a2JoTGJiaW54VkQvZ1o2NHVPSEpMQTdycTlDQgpycHdFWEZyY0E0K25BVXRiMy9ZTW1yRDJBUU9xS2o5R2ovcmZQbEhXMXdJREFRQUJvMEl3UURBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCQmpBZEJnTlZIUTRFRmdRVWVYbTBkWldoUVgzVzEzUEsKSE9VMHo3VWY4ejh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUk5a01TL3hnbk1zbEVOMU1xK3ZuT2NOV0xtZwpmeDNHTGkrd2hvVEZsckh3bkIzRGVNLzBCbGh0RGVnM0pmeHEzYTRPQlAvS25KSm4vZkcwVzBlR2ZzeWU3d1I3CkV4Y3dkU3FEMjV3czIrRjdFL1B5R0ZNUzFNNHROWitiVEU4M25YU3JuOURBczQrbUNhQzRFaCt4UWg0UHo1d20KQldKSjhzUnhNUHBIZE9iVHlienhNVHo0S29tVGZ2ZWtpL081M3pwRDNDbEV3MVRhRm53S0FTWEgzL2lkZUg5bwo2ZjhPQVdUVHV2NUhCSlZBUzRpUWZCMG1kVkhUVjlGMnk3UHorb25WM2p6c3hpZlVET3hvTXVwYzZHMWNHb1dhCngrdmZBcUl1dVJWY2IxbVZHdG9kZFFrOTZwa0JsalkzNWZCdFYzdHZKMXZ4VERxY0Uxak5TVUp3Tmk0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://148.116.85.8:6443
  name: cluster-cnxbbbob2ja
contexts:
- context:
    cluster: cluster-cnxbbbob2ja
    user: user-cnxbbbob2ja
  name: context-cnxbbbob2ja
current-context: context-cnxbbbob2ja
kind: ''
users:
- name: user-cnxbbbob2ja
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - ce
      - cluster
      - generate-token
      - --cluster-id
      - ocid1.cluster.oc1.ca-montreal-1.aaaaaaaa2igg5dycbg3qzpbljgb2czew6f75aajtchbuxjuc7cnxbbbob2ja
      - --region
      - ca-montreal-1
      command: oci
      env: []
