apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-cron-lego-volume
  labels:
    app.kubernetes.io/name: letsencrypt-cron
spec:
  storageClassName: truenas-nfs-spitfire-fast
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi