apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  labels:
    app.kubernetes.io/name: unifi-controller
spec:
  storageClassName: truenas-nfs-spitfire-fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi