---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge-data
  labels:
    app.kubernetes.io/name: thelounge
spec:
  storageClassName: truenas-iscsi-spitfire-fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-data
  labels:
    app.kubernetes.io/name: thelounge
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
