apiVersion: viaduct.ai/v1
kind: ksops-exec
metadata:
  # Specify a name
  name: immich-secret-generator
files:
# There's a nasty problem with kustomize or kustomize-sops which
# tries to load this relative path in relation to the path of the
# kustomization.yaml rather than that of this file.
  - ./secrets/immich-secrets.yaml
