apiVersion: v1
kind: Secret
metadata:
    name: lanparty-seating
    labels:
        app.kubernetes.io/name: lanparty-seating
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:NdhOMB/VnXlsgjT8jVDaFQpwD6IojvaeRGjVy4G464zsJUHQ7oBaHxXToYrhgPz0fBQ6hQAhRVO30I/Y81T2CQ==,iv:eivY9cr3oktd15mLdJc/df6JkrI7q/YV14hSmlt+nM8=,tag:06bJuEE00jizX7wkfkEyTQ==,type:str]
    RELEASE_COOKIE: ENC[AES256_GCM,data:s9MoMnCVCKWKyzGWfB1dYMvVP9pTp/USN25qNASm1ZFdZplUUsI/VgF6dX6nw2puhtEWEyj8Rh5tTmqPhuIx9w==,iv:AvSsSAKcWWaPMiyuiZ0ddD8gwxKzqTioO8H1Z6/AOk8=,tag:5zTNxD0hNUX+KKGlZBwoNg==,type:str]
    OTEL_EXPORTER_OTLP_HEADERS: ENC[AES256_GCM,data:Or16q2AIM74zK+7rZBmOXwNXnyJZToMqQLSPnhhRjievexAICc5BvJpZy74TvOZ6WCwIKtmKwZ+yLcFyiamx7M7t33NIohkM8pXczzbJVY3B,iv:vjHNbcwFF6QFiLVYvv9zUu6qah28QGsVvG8wnnfA6BQ=,tag:C44IOMJm2ukKLHWXkbSe0w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:8DmBpNGbTz6v8DiX9kgEOSAadThxZdyj8aO/p/hZ74c+kEunddfGwycrabVT7LScyKhQODmp3/hWxFP0QVp2LKMS+XHEEmdJtC+Q6NpTBMjRXUBsevHxEkbnlVjMXDXBnGbD9nxwYhQDt2LD8+mm7lZ/6nLAxqDzprclSPXnqPj1XpfhDSzc5WTUMzLRBrZRAH3IDaPYLSXrWUxtVenUZQ==,iv:uw2/2nuWSaptjWG07BIaFiLzsC6ed9KVK/aznRW7IXs=,tag:LJhDCa05pBmIByhtsIQzFw==,type:str]
sops:
    lastmodified: "2026-01-25T23:11:08Z"
    mac: ENC[AES256_GCM,data:eVTi5TkB69nEq+8N9cerO2pTM6wxqcj5LNqWSiPDrEBLa1VKAr7sHKRZaZ/kaUlW/DEh/Hjgxf3oaOdeNFHLeJf3P5HbSWnHKxSlh0bgAOH70owSSNyGqc2lVdeZ7ejaC2xU4MLmmc+8DCFPnJdlGiDfzPRUXVIK6A97PwaJ/Hc=,iv:W9CNc0MxWen+UcB5XBUjq2VkqMy5806a7KoWwLus+aw=,tag:4KQFuvU7cNZA3O3fGrdNtg==,type:str]
    pgp:
        - created_at: "2021-12-28T04:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYARAAmBVcYXyzfro48bPFf08XRa1EjlBW/+SEbhbMf/2EhDWy
            z/YbKk2QMItWPTVLcNffm8F3a+MXTJPQlqySvksLMufKBqb4L3j98UNrErbEnJ1f
            fHg680bB6s3VJKB7WvA1RLyU9PofIijIS5ze4AiUn86LXfPj1c7dZaRc1S14wM3x
            rSCLxmk4DFksEjbigw1l7WpoqsUL2JfTVbYxrRbonCHzSKqxBghq3bP8ER1FQmeF
            UgJ5aUVibjnKSE+bPLSd6wxJbje7Ucplu/uDOOAmY2wHGifA4A//QLmSsaHBKEv5
            jEy6680Avpg3xhSGs8OS8UNI9+MyfaTiTKOThvMNaf7DTAKmJ4hOe+nW6dPeXUPe
            iUSnHB3ab84LQ2PWlza1xBmOuFMn4cySwidmBz3OOhfqGaUY4BE2Bz+jX1v2WqeZ
            h+HRnM2sL8ea1m3xECbgUzbQvIfq9NwMS4gFGI2FFSsx65lJh7bI7ua6oeMZlhfk
            6YLrqyyjrCJ8qQXcZENGv/OyoRHaWPOtWf0kOr4Wop782suxDWhmBocd0crJAngo
            NPHgHucDd2DdDS8jA+UtKSrFja3EJKsq6cJ/NDaIOWWO6vOD9dQbItEeKlrxJqzj
            xBln+25XD1VYpC8ndYXgNfxarPVYUXfJWUuat/kPCFVnCE2N3YQB6nsxFlPUhgLS
            XgEc28DSkIRY5H5Qv9XzjWcc0z6BNSmDauTAvap3PDCv6X7grZYzUbEm850Oz544
            seXDyn3XdApYiK7VYzaLG4iI5JGHmk/l1vgY21w8004AYXaIXEGFHQCeI54mxow=
            =nWNo
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-12-28T04:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/+IJ5HbJZtzHX4aZEYKNEzMZxbl1dfZBACshqTIZpYwSbg
            aUpRdZiur5KZik8SswkDjHER2E6udepWwPt8IhK40tF4fsxBQ4fw3/Qw6otfMIEg
            NoAuaC9nyuuYKpZnpBdl6bAXb6NLWu9WdHt5SZ4Ye7D0tThdIDN4jqc9b6EcBt0h
            xO5N1RQ+M7bUl762UhJg1GvvTW1i+5E+TqtBmtfl84nBcCI7GNBbaJAzYyNQFtyb
            p3GOdRFfngpnLOi9LbUSFGKIZb3DhI+guZAffEsJR48TF9gVZC2jro08jQpk2m/E
            QiPjxbftzB89eLLRjf5Cm/Pn7Q/amh/mN5NWoBShfbtHpArp2lnJ3fGJKno58M8M
            sK/YXI8GgbvGWJBvfFDI2pmlWGH7xYTKelhd6A6zpt7KQu7kl/wxgLc+0v6QZ3en
            zoKrhR6drdEFtEqazruhnq0ZErYbCTPFIyoiwWy5mysgMEKJ756tZG0ZJbWCMY5W
            ngwoA8T5Og+BG/LveZwtcPvPBZa9qGcHhGHBcH35GnlZJhZaKqxQjKa8jJlTy683
            mtCQhvrFZUiJlQObIe7PWlP+yfOtm5+MeO4wc89OYb7eQdsMGl/aX8GT1Ev5NUH0
            5hiFpPjWOdz9pznp23MTdQJMXQ+5n0fXcVWCo3oU13Ldo82mqgN53BcfGcf+yCzS
            XgHoxj7sBxeMZ60izc50dcJDcbrzmeG7r8axrtwU6B+ByrL3W0s+UMBCtJx8ZUnk
            gtBRBuRWIhj3ON0LT/lIWHoL0XLYXiV/ujC+m4dBn9wc/SuhDccbb6rDprGZ2TU=
            =iQu5
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    labels:
        app.kubernetes.io/name: lanparty-seating
stringData:
    username: ENC[AES256_GCM,data:B/BQ0Qf5jp8twFNN3l9/1g==,iv:BqUORJZcilH7bluY0QLx+lTFgCk2cKmrl6y5KjV87q8=,tag:tyEfP939Z6r+n94WbCddog==,type:str]
    password: ENC[AES256_GCM,data:V5ARJeaW9P+zB/u0Wg3nKgRUIaVHWzBiw/Ft2adOgrPfWznBO1FkuOmPfkxGDefQrTbjKj3N8FzniTek0UJsgw==,iv:WUT4varAvy488PET2OIG6NUYz9bsDbtIQUNtf4YbShs=,tag:V0iv3oNZqjKaNO9QNChrjw==,type:str]
sops:
    lastmodified: "2026-01-25T23:11:08Z"
    mac: ENC[AES256_GCM,data:eVTi5TkB69nEq+8N9cerO2pTM6wxqcj5LNqWSiPDrEBLa1VKAr7sHKRZaZ/kaUlW/DEh/Hjgxf3oaOdeNFHLeJf3P5HbSWnHKxSlh0bgAOH70owSSNyGqc2lVdeZ7ejaC2xU4MLmmc+8DCFPnJdlGiDfzPRUXVIK6A97PwaJ/Hc=,iv:W9CNc0MxWen+UcB5XBUjq2VkqMy5806a7KoWwLus+aw=,tag:4KQFuvU7cNZA3O3fGrdNtg==,type:str]
    pgp:
        - created_at: "2021-12-28T04:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYARAAmBVcYXyzfro48bPFf08XRa1EjlBW/+SEbhbMf/2EhDWy
            z/YbKk2QMItWPTVLcNffm8F3a+MXTJPQlqySvksLMufKBqb4L3j98UNrErbEnJ1f
            fHg680bB6s3VJKB7WvA1RLyU9PofIijIS5ze4AiUn86LXfPj1c7dZaRc1S14wM3x
            rSCLxmk4DFksEjbigw1l7WpoqsUL2JfTVbYxrRbonCHzSKqxBghq3bP8ER1FQmeF
            UgJ5aUVibjnKSE+bPLSd6wxJbje7Ucplu/uDOOAmY2wHGifA4A//QLmSsaHBKEv5
            jEy6680Avpg3xhSGs8OS8UNI9+MyfaTiTKOThvMNaf7DTAKmJ4hOe+nW6dPeXUPe
            iUSnHB3ab84LQ2PWlza1xBmOuFMn4cySwidmBz3OOhfqGaUY4BE2Bz+jX1v2WqeZ
            h+HRnM2sL8ea1m3xECbgUzbQvIfq9NwMS4gFGI2FFSsx65lJh7bI7ua6oeMZlhfk
            6YLrqyyjrCJ8qQXcZENGv/OyoRHaWPOtWf0kOr4Wop782suxDWhmBocd0crJAngo
            NPHgHucDd2DdDS8jA+UtKSrFja3EJKsq6cJ/NDaIOWWO6vOD9dQbItEeKlrxJqzj
            xBln+25XD1VYpC8ndYXgNfxarPVYUXfJWUuat/kPCFVnCE2N3YQB6nsxFlPUhgLS
            XgEc28DSkIRY5H5Qv9XzjWcc0z6BNSmDauTAvap3PDCv6X7grZYzUbEm850Oz544
            seXDyn3XdApYiK7VYzaLG4iI5JGHmk/l1vgY21w8004AYXaIXEGFHQCeI54mxow=
            =nWNo
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-12-28T04:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/+IJ5HbJZtzHX4aZEYKNEzMZxbl1dfZBACshqTIZpYwSbg
            aUpRdZiur5KZik8SswkDjHER2E6udepWwPt8IhK40tF4fsxBQ4fw3/Qw6otfMIEg
            NoAuaC9nyuuYKpZnpBdl6bAXb6NLWu9WdHt5SZ4Ye7D0tThdIDN4jqc9b6EcBt0h
            xO5N1RQ+M7bUl762UhJg1GvvTW1i+5E+TqtBmtfl84nBcCI7GNBbaJAzYyNQFtyb
            p3GOdRFfngpnLOi9LbUSFGKIZb3DhI+guZAffEsJR48TF9gVZC2jro08jQpk2m/E
            QiPjxbftzB89eLLRjf5Cm/Pn7Q/amh/mN5NWoBShfbtHpArp2lnJ3fGJKno58M8M
            sK/YXI8GgbvGWJBvfFDI2pmlWGH7xYTKelhd6A6zpt7KQu7kl/wxgLc+0v6QZ3en
            zoKrhR6drdEFtEqazruhnq0ZErYbCTPFIyoiwWy5mysgMEKJ756tZG0ZJbWCMY5W
            ngwoA8T5Og+BG/LveZwtcPvPBZa9qGcHhGHBcH35GnlZJhZaKqxQjKa8jJlTy683
            mtCQhvrFZUiJlQObIe7PWlP+yfOtm5+MeO4wc89OYb7eQdsMGl/aX8GT1Ev5NUH0
            5hiFpPjWOdz9pznp23MTdQJMXQ+5n0fXcVWCo3oU13Ldo82mqgN53BcfGcf+yCzS
            XgHoxj7sBxeMZ60izc50dcJDcbrzmeG7r8axrtwU6B+ByrL3W0s+UMBCtJx8ZUnk
            gtBRBuRWIhj3ON0LT/lIWHoL0XLYXiV/ujC+m4dBn9wc/SuhDccbb6rDprGZ2TU=
            =iQu5
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
