apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  storageClassName: truenas-nfs-spitfire-fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi