apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/namespace.yaml
- ./resources/gateway.yaml
- ./resources/dummy-http.yaml

namespace: envoy-gateway

helmCharts:
- name: gateway-helm
  releaseName: envoy-gateway
  valuesFile: ./resources/envoy-gateway-values.yaml
  version: v1.3.0
  repo: oci://registry-1.docker.io/envoyproxy
  namespace: envoy-gateway
  includeCRDs: true