apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resources/ingress.yaml
- resources/nfs-volume.yaml

images:
- name: viktorstrate/photoview
  newTag: "2"

generators:
- ./generators/secrets-generator.yaml

namespace: photoview

patches:
- path: ./patches/persistence.yaml
  target:
    group: apps
    kind: StatefulSet
    name: photoview
    version: v1
