apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lanparty-seating-postgres
spec:
  instances: 2
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        cnpg.io/cluster: lanparty-seating-postgres
  bootstrap:
    initdb:
      database: lanparty-seating
      owner: lanparty-seating
      postInitSQL:
        - CREATE EXTENSION citext;
      secret:
        name: postgres
  storage:
    storageClass: truenas-iscsi-spitfire-fast
    size: 5Gi
  monitoring:
    enablePodMonitor: true