---
apiVersion: v1
kind: Service
metadata:
  name: photoview
  labels:
    app.kubernetes.io/name: photoview
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: photoview
