---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wizarrr
  labels:
    app.kubernetes.io/name: wizarrr
spec:
  serviceName: "wizarrr"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wizarrr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wizarrr
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: wizarrr
      containers:
      - name: wizarrr
        image: ghcr.io/wizarrrr/wizarr:dev
        imagePullPolicy: Always
        # env:
        # - name: "HOST"
        #   value: "::"
        ports:
        - name: "http"
          containerPort: 5690
          protocol: TCP
        volumeMounts:
        - name: wizarrr-config
          mountPath: /data
        resources:
          requests:
            cpu: "0.25"
            memory: "250Mi"
          limits:
            memory: "500Mi"
        readinessProbe:
          httpGet:
              path: /health
              port: 5690
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
              path: /health
              port: 5690
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: wizarrr-config
        persistentVolumeClaim:
          claimName: wizarrr-config
