apiVersion: v1
kind: Secret
metadata:
    name: vault-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:HkKvl38EvdeXQfZ9bYFmaTIT9ro/yAtPh1LPz+k+jjH7DN02/2a4hw==,iv:qQEu38fsHfbd8FzWrUBXr0NxnRiItrLMB0YmESuXMLs=,tag:nBdkPhGv+q0todzyCHFI8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T05:02:09Z"
    mac: ENC[AES256_GCM,data:qWl33WOE8Y16l/MJ+lLvyvmwHwha+ijp0iSdrAu1J55wINDpgxkPRJ8V5HOZtxYmQ5DOqOPdjb+kHhUAdTNg4BF32Haxzc1XJ9qVJTrITBMqcKcBhR/i+4LuXFaiIJ3Z0t0kCanWuoS6OurRIhENEAf7Ggre84PaSDb1E26q+AQ=,iv:dZjzKeuwgE8yYHPagtSMZTxvWbsDiWPU8Rbbd9pdACs=,tag:LRlUannvzecv5HVAOVFG4A==,type:str]
    pgp:
        - created_at: "2025-02-27T05:02:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYAQ/+N23MT038udbHb3yXe0Uw38DkKHdbT9in3xNiDGfauWGv
            THM1nZf2ys6kNLHFVrBloGkMJ8epcB0yW0foAgR9QxGBH6d68SSSQZuQrJe0Fu9H
            KVGqnNxrQh9XPveJDROQ4x464byoAh8M+zw31rkxclT4aAT5RD2iB7iEF0R0EnCM
            l+qhybrV0v3VsSnOWUd/8mABtKI2NYRkC1o+bAi3n2GGgR6uda7/61RVMtJpf28u
            4fUSS8DGQ8Wzal81oS2BA9WIBVFZvMHlNkSOpXMiKqM/YASzk73/xtA+pfH6EbdN
            jvC4NyVLKqxAWQfLPHp/8Iu+odIQbCkj0GYa3nQnWEvRMzfuFiE7cF1OEbZyxg0X
            Sh/5vBX8R0C1sM4O7SwUmi3l5TTQ3HVp32PKV7e6TWRny+eghah7oB0rOwuxHJ8I
            Vu+BzKeSc41U0XA9M5nilvxn/rKZGWDf7ifuQ0J/RCo1+MD3L8RszC52AQS6t178
            SH4w7zZfPHNY01ioZYWGlF3uTREKtsJgfcWa8ZB1rLm9rBm6c+8jZ6025NY52BI6
            Fto6HymUH525IEy+MCay7hJ67V7zMWpjBNWpsmBUgJ4x8YRAmRfkmBMZnF3ImZ/B
            N6jxB3lEVodFl6sHtBBaw8J+oSl+V862FD5rYpd/58QZoJW700efqA+X97UHkZPS
            UQHGvlOdcGvNJ2iQHiukLDnY/xZ7SjxYZS0ypuJp0/vzFd0PqM58xDzOVk0TO5kC
            82tukZIHkt1jJAlu857nDsGaZHlGlARW/8DgJ5rTXbfzLw==
            =MNgO
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2025-02-27T05:02:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9AQ/9GWZ34UWJO/h7VuHdKiY9DFklGsfDtWouzb6PuVFrl5o9
            yk5scWC82gdVY7Av3sPxcbfZLRqM4l8+ZDguBgBVDppPsFscy9GLsEK+NdhGVi4b
            tNw/vOHce7TYgEAfnfPt34IDtZLkaegQCWBItPz2wHaN26JTGjFHcQSLdkMX+f4j
            eQiqPHHVGUURDGZhoy/2CiR+6E6qF2j7qrH8Keea1p0+NYVtcLF2SyawFaunfTt0
            MfFeHKcmzg+kHv4zbtn0d+1ba/fJ0r5jXS9TWdVTbfahE5kTF0ZBT/qpXdcH2w8U
            dvXYIoE+8H6vCdeAdWAoe5sjReJ0DHdTQj17F6/cr8BuERhmWhXl1DOuWQrlYc6K
            G51f9CEu9tCV+8NALMTa9aq7RvZk0wqkWDLxCbhbWgEwR++xMg1UVg2DwYxUjAVH
            /uC6uDml/GEKwMZlJWke2y+Uqydz2AauRR0+7klZI9q3ZnYekR5hvmur9sLDNkao
            SUn9yT6oEcxHU+50gDAK1ODnPGwU56m9xYat+Ar7JyvIInlDtLngM9aQyzZlqgf0
            rmOtgZu3wzgDkTyrPsO3L5PyUKdFuzniLM+G9G1aAAKn0vk6IjZ4FduQO5isPAAZ
            5eZ99UeN5wZtlD8zc8DExPRhgeOZ8r469AhUwP5A/beWDHgWOMP9/XLSdRh6g/bS
            UQHFj84JlrRKXpWaCGPJKZ8JXFlfJULrozxRdpb0JOR2gT010fzw346oVS+2hIjB
            KMa/khu9socWdBkm7n7TLQbTALHxCDdErlZgOl/RwysvdA==
            =WLZ4
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
