- op: add
  path: /metadata/annotations
  value:
    external-dns.alpha.kubernetes.io/hostname: gtnh.k8s.305-1700.tdude.co
    external-dns.alpha.kubernetes.io/target: 76.71.180.2,2a0c:9a46:637:88:3::22