apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: minecraft
  name: srv-record2
  namespace: ftb-academy
spec:
  endpoints:
  - dnsName: _minecraft._tcp.ftb2-academy.tdude.co
    recordType: SRV
    targets:
    - 1 1 12354 ftb2-academy.k8s.235.tdude.co.
