apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:JF/lgBn3af5TmXwMp8BpFnDFfBg+BvWXcmtqcBkvl+o=,iv:YEyhsPA7A299azW7UeXSNA7meA4OJe5mumk6m0jeSUw=,tag:5qOvR/ms65k+RAp0mSfZLQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dm+FPDmn/8bqijHLQsAsXxdCHsg+K3/EYh87PbzOZcg=,iv:RbbdtouvzZWFYtbTOXhE1RUUIOOjKJTv12v6m3trTLM=,tag:L1aX2wgH7E7dNopA2AA5sw==,type:str]
sops:
    lastmodified: "2026-02-16T04:29:58Z"
    mac: ENC[AES256_GCM,data:JWCj0dZo7E5s+T7gjY9v+BM52FEodAUkJrcwVu+aoUT+Otm02Azhpxx+JKQt+pqF/VSlKVyMx5oD8IbU5U8eYE6uiIcTcsYbtsv5k1xrMEtXtuQsHqZ3/qTXlinAmi2kMGQRniauXWW2ei0u7m5Md3smGcYPdR6hsq/LnCKgrRk=,iv:z1YhFW0ppZnMLF9ySWLoMS1tYcWTLo8dGWS7LwfIerI=,tag:dWLMNIBq7tTnz9MnjciFlQ==,type:str]
    pgp:
        - created_at: "2026-02-16T01:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYARAAh8aUFPzp+NTX0j0c0D6OigrIb//fTWEUWk2O2YqsKuyP
            PFLzwUm/RtI+AVqaaBYcJaEHIJq8uN/fWOpVtPuOBYm+rX3H/hXGXPki/XhYiFVC
            HujR5VREYrBpRpEa6NU2diMYUvKPhoQdxbVYRl5R1AIgiZlQBFxm3MRkQkM2+0Ly
            fNBTXBhmzfIYMh9xFnihn7beI1f3I3jL1kcEdtFdvZ6roqObw7cR+U6r3AaOZYVs
            Z7JcJpCc2dcfM/QkGfxsxrY/KH4Mxuhh5Ag+k2G5fzjOTNR8SYeODWl2IU0aD5lT
            JAoHVEfd5+yelbqcG7Th6HZoKHqL3vKsYHXQnUZMavZmmdwMiIcz1p9sOmRO7OMb
            +EyvyM5vKhlzQciCHamz2n6/Bl/oI//uB4LZTm3Z0P1H5kuUBDY+RElspQfcfvrQ
            LPQAbyaujA7v+5YnSz+P2OZOXCEfiDwVbF5MBHN8lGSgJvzxOU2hBocj0+bsWaUj
            MeY8NaTqpuE2MB2ewBh6VoUr0WLooeJ49zUuvqNhfryUqY8x5xI33T739KLeNnu+
            jCphdgjJ6HftKnLV3sWGK4RWSS/KQltvW9nAo1P+bFzBiidqykHD5pZRBnBnPcWj
            i/MiX/IMbHKm26TGrjyAnJBR6Psn1g/6F6zqtvo4uOjcnx3LpwjYLEsXh0Roxv7S
            UQGsG8qGv7RhdH0eyn7yczSM2b9KkCxtTNsORZ0svu8M2L1ElhCNxspDt9etS5+Z
            CMmH8wySfL+alHbEb0wOPTk7jT80ZWLO5WyWZ4y949lvKQ==
            =rBfH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-02-16T01:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9AQ//R2+5mQ0Cnsbj2zGdV7Aqb6EEoRizWvn1MLBgzL+w229h
            r9wg6leV6sCj030Lt1pM8fWN4EXjufe3p1+B59NZy5Q2P7sWpGweDK98VVbgCxTO
            Zi7K74lbEpfxJEXa6Tx+KR/9pDTxUJ5AjJY273nwf5LAS7YwVKeV3kXPoY2ZwpqU
            s4cnxj7iUOBRpOmWHP670YN0rMb6DlI0tqdDWx8nOGKQR1gEBP3UgDgPHZ0zRnwM
            IElm5ktQo5bVOWP90DFOzIIE3kJ/BOzq2BD3FDFOW2FQE+hzxHp/akfx6XpP9mte
            X0lozrKM39L9w5qVz5La8Zd5fgcM7G16pc8z0XFYDrQMZ1KVpfGJ8ThxJf6zcPay
            r6I2nYxHkV27bTKunpsLUn934PUrMP4HMu7c5qIQ2uItouZ+pQpxhJ9MHASOjE95
            H+dDaYp6FWOYrRJxrzEBnBwRqElxjhO/Cxex0rKlHIGBK+T4VN3762Zk6MWvJ8yK
            3YhaaPjb4WGe8QuWQW1KF0NfHV1brGu9FVERDECRuFNcMnMdYBor0V4nMdjyVt7/
            pwOk5ImjjsoQpYt/8lPH3PVuijQzR367SRv+gh5mtI2c8fm5lzogWJDtF5ScL+IN
            yJatFuzhSfWr/GgUfEu3CS5DfQNIDnLiWMCNS1R4IC7w1rSZDumzb4oH4ETkcNXS
            UQHI0H9SGrHFpfNZ82EKBSbgLB8mqKdFiX0MNp1sy05berTpMTOoW9fN/eJp10UO
            f/jsyvp/r6LtOwENw/fP/PHtxQ6SKIeAaEg8zotTSoKYHA==
            =g4Bv
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1b9mDEId,iv:+LdBvxntBhS2GtL15D5qwGjIntZx+JkcwzESEMxiocQ=,tag:FqAyVNml3CP5tKRnfOIKTQ==,type:str]
    password: ENC[AES256_GCM,data:jTiSrK5GfmzRtAoJ8PuCLIkxpk0bGKt3SjwC9KBzVRE=,iv:UALDabR/6s/jUGh95DTnplWAArNHLAuz2HmJAuxzTfs=,tag:YBaBojZ5f8B3MP3hR5qRWQ==,type:str]
sops:
    lastmodified: "2026-02-16T04:29:58Z"
    mac: ENC[AES256_GCM,data:JWCj0dZo7E5s+T7gjY9v+BM52FEodAUkJrcwVu+aoUT+Otm02Azhpxx+JKQt+pqF/VSlKVyMx5oD8IbU5U8eYE6uiIcTcsYbtsv5k1xrMEtXtuQsHqZ3/qTXlinAmi2kMGQRniauXWW2ei0u7m5Md3smGcYPdR6hsq/LnCKgrRk=,iv:z1YhFW0ppZnMLF9ySWLoMS1tYcWTLo8dGWS7LwfIerI=,tag:dWLMNIBq7tTnz9MnjciFlQ==,type:str]
    pgp:
        - created_at: "2026-02-16T01:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYARAAh8aUFPzp+NTX0j0c0D6OigrIb//fTWEUWk2O2YqsKuyP
            PFLzwUm/RtI+AVqaaBYcJaEHIJq8uN/fWOpVtPuOBYm+rX3H/hXGXPki/XhYiFVC
            HujR5VREYrBpRpEa6NU2diMYUvKPhoQdxbVYRl5R1AIgiZlQBFxm3MRkQkM2+0Ly
            fNBTXBhmzfIYMh9xFnihn7beI1f3I3jL1kcEdtFdvZ6roqObw7cR+U6r3AaOZYVs
            Z7JcJpCc2dcfM/QkGfxsxrY/KH4Mxuhh5Ag+k2G5fzjOTNR8SYeODWl2IU0aD5lT
            JAoHVEfd5+yelbqcG7Th6HZoKHqL3vKsYHXQnUZMavZmmdwMiIcz1p9sOmRO7OMb
            +EyvyM5vKhlzQciCHamz2n6/Bl/oI//uB4LZTm3Z0P1H5kuUBDY+RElspQfcfvrQ
            LPQAbyaujA7v+5YnSz+P2OZOXCEfiDwVbF5MBHN8lGSgJvzxOU2hBocj0+bsWaUj
            MeY8NaTqpuE2MB2ewBh6VoUr0WLooeJ49zUuvqNhfryUqY8x5xI33T739KLeNnu+
            jCphdgjJ6HftKnLV3sWGK4RWSS/KQltvW9nAo1P+bFzBiidqykHD5pZRBnBnPcWj
            i/MiX/IMbHKm26TGrjyAnJBR6Psn1g/6F6zqtvo4uOjcnx3LpwjYLEsXh0Roxv7S
            UQGsG8qGv7RhdH0eyn7yczSM2b9KkCxtTNsORZ0svu8M2L1ElhCNxspDt9etS5+Z
            CMmH8wySfL+alHbEb0wOPTk7jT80ZWLO5WyWZ4y949lvKQ==
            =rBfH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-02-16T01:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9AQ//R2+5mQ0Cnsbj2zGdV7Aqb6EEoRizWvn1MLBgzL+w229h
            r9wg6leV6sCj030Lt1pM8fWN4EXjufe3p1+B59NZy5Q2P7sWpGweDK98VVbgCxTO
            Zi7K74lbEpfxJEXa6Tx+KR/9pDTxUJ5AjJY273nwf5LAS7YwVKeV3kXPoY2ZwpqU
            s4cnxj7iUOBRpOmWHP670YN0rMb6DlI0tqdDWx8nOGKQR1gEBP3UgDgPHZ0zRnwM
            IElm5ktQo5bVOWP90DFOzIIE3kJ/BOzq2BD3FDFOW2FQE+hzxHp/akfx6XpP9mte
            X0lozrKM39L9w5qVz5La8Zd5fgcM7G16pc8z0XFYDrQMZ1KVpfGJ8ThxJf6zcPay
            r6I2nYxHkV27bTKunpsLUn934PUrMP4HMu7c5qIQ2uItouZ+pQpxhJ9MHASOjE95
            H+dDaYp6FWOYrRJxrzEBnBwRqElxjhO/Cxex0rKlHIGBK+T4VN3762Zk6MWvJ8yK
            3YhaaPjb4WGe8QuWQW1KF0NfHV1brGu9FVERDECRuFNcMnMdYBor0V4nMdjyVt7/
            pwOk5ImjjsoQpYt/8lPH3PVuijQzR367SRv+gh5mtI2c8fm5lzogWJDtF5ScL+IN
            yJatFuzhSfWr/GgUfEu3CS5DfQNIDnLiWMCNS1R4IC7w1rSZDumzb4oH4ETkcNXS
            UQHI0H9SGrHFpfNZ82EKBSbgLB8mqKdFiX0MNp1sy05berTpMTOoW9fN/eJp10UO
            f/jsyvp/r6LtOwENw/fP/PHtxQ6SKIeAaEg8zotTSoKYHA==
            =g4Bv
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
