kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-datadir
  labels:
    app.kubernetes.io/name: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "truenas-nfs-spitfire-fast"