apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-200-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-200
  template:
    metadata:
      labels:
        app: http-200
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: http-200
      containers:
      - name: http-echo
        image: hashicorp/http-echo:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
        args:
        - "-listen=:8080"
        - "-text=OK"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-200-svc
spec:
  selector:
    app: http-200
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-200-route
  annotations:
    external-dns.alpha.kubernetes.io/target: "envoy.k8s.235.tdude.co"
spec:
  parentRefs:
  - name: envoy-gateway # Reference your Gateway resource
    namespace: envoy-gateway  # Replace with the namespace of your Gateway
  hostnames:
  - dummy.235.tdude.co
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: http-200-svc
      namespace: envoy-gateway
      port: 80 # Match the "https" port specified in your service
