kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hedgedoc-uploads
  labels:
    app.kubernetes.io/name: hedgedoc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "truenas-nfs-spitfire-fast"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ctfnote-uploads
  labels:
    app.kubernetes.io/name: ctfnote
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "truenas-nfs-spitfire-fast"
