apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-nfs-spitfire-fast-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:MV26eWJ0ITxfTpI6K2s0FfjRNDD1rqMG3Ct9LPU66flmjQ1a1dFktCKKOfH6SO6Lyy22NRXzBcaa/4PHmezqTGlR0nkcXMV33qF51U5t2eM5XKNpGkZ4KNHN8YdI78NuW1/O6W4APPWI6Lysz4SeHx7Y7I6oG9O+qwkgyjLmS0K+4K5vEpPZl9a1KRakYCJff4LrmD/7BYG1xUW4P6HKBzxLQZ8/TalGdc4TOafW8YbUIdGZfs+yh2FW8bZvz/Bto4evN87mjOuFONRVajsqqZbzOrTj6iLIdO43K3mtyvGc64h3XPNX1RVZqrxS+Rk/Lh/uRUwi+eDcoIb2Ikg0oXzVHfyrzo8ZvFxoKkTpqQlTnCJvdXPFKpsU0xhzcgd4421Zty5yA8G0I2crwz9Vjj/TU8yUBy4oazF0KWhece00g60gsDmkxRnNGyTPpL9S3OPja6O9ECELgk1a2y3HYiSqtKXgz/aDNQPZkHlfvVEWV1WDfGBf1A3lCuE7SQF9vQyO4zpsrycOiV/BcfW4W9yVpXoBJGkTKAqPv19ugYw84mY2KsKtAn03BWuo61q3J6cFuwS4vfNEDlQi0QRWw+yCj6Ong1k6FFsP1VzmtyARsQSvQxTBaLajnbYSAArQL7VmAWsjQvRtdvCcebb/3zNS0/cr8D2UdcklpSLG4NTtJ7kGGnzp3S1pk+2YrQkqGJpH/5KQnrCzCcuZ3RsqIQKEFxGaIuxFRWMG2w44blwC9mCVQ2Qv7BoFg+lDcga5v4IxcvrqGi0uWI2nExl+UhW6+L9GR3BcS51T9VmAF5PSVoXVDzinVDRj93nMahgFao9A0bDNQES45FdmxLd67PP8cdL5bRSxXf85S6LnprWGuKNPwKI04uxAPk7o0YUhaVjvjvK6nS4RxyEoN9pky0a2rQONIK50dSbIERMfa3RPrUYJ7adeGT3PvswzEs/uLQ3Q+e0qN3b9j/beCWqwd1bZA+bvd07z7DeroIpp4U3V8YoaQbI+nMl23V0eelF0lziBe1e2BwLeoojpMkPzIqXHwNwqtD1T+gzpfclzXzpsrdwD7G/vOvmsNK90tmwEaawQuvHMW+Cxs87HgoSLmBjskBiaGeheGr+MF4fgsRlCB39oMUMXnJw6enstnBE6THXjVo9fIPdogeFuP/35UeSC+LVfPz2fN0IGc1kf9pi8weRs/7yIF7/FgtS2WlPbXoLHeFoH1od0FckMkujeo/SZ9RKzeajz3NOms6ru/W7HhuhFCvNKJsvTHk1QgPFEwB0qwqEr+teqnHS/yUCbJvTawrJBsYPbHOw5Tvk818J85H3LaLd4POQIxuUvPPWNU55X4ykE8Bx+v4brdezN7UvdpYZ+IXRm/l9/RbHh45fsJz7q/QNa/JIEH+3fHbjbPmdpcNo5F7Udc7k6XFa5Lf3lluroVRPxX8lweZLMixV2DsxGm4jppEr4fEuKHL1QBB+UADtr58l7G8j6fCtBtOrI2IrQGQDwmvOl7Lyhvf+MHxz24YP4tmcjdVaodpvrYP/9UPm6Kv0aTslJe0z9v6HHtZZgmrd+8FKsaZkqSyhfNym9KqbmsgM0GYLYUjx+Op1uhbX1HHoOmum+oBi7ndH1Pha/mk8d3duF2IqbuAgaKZW+sv+/++2ADKz1GDdq/ZqYeNiM+Vf+waRtedONXLGc/dpBqIE7nU+jBTcfuqUhTd593Z0+5HP1B8hQE99UhnrZ9XGleA/5+Jb9Ol/lLyV0D6Kh5lIsCoq3m956UvD80lcoQeBqJxD1G8yJxr64CLLN67EyXBidejjlc3a/UjoQVaEFpFxX/yoXydizczmgkLdU/ButgzKNlYUymqSPf4aFOYJ+vkFWzQwMocyDG97fP3fFsWatsFqkukQOwMPbGQgmgOHlsWPhikZY+dWU/nGeK7iqL4hh4A2UhsYUVlSSdKNLZtgYd49Q9PlmNOHOznIwiA7naSlbGbl0QiqxAjUYB6Mqn4HmUVy68oIt60aXSTPybE33sVgLV7ZyWR3ZYpzXUqn4P+1cV5a6un5UX1BR0eb4Qjib+IiA,iv:97QEvjLsN9ZYmhSQ9AqvJsrf0pcu+wDaFYb0If+Ijac=,tag:t86WqmoV4JmhB9YTJwr5XQ==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T04:49:46Z"
    mac: ENC[AES256_GCM,data:3wOMNIXybF3XuIASf9+LXTNs6GFVn9wHVHmgVIlvWBBuwONfxCMWE02VkWArb56c6ssT5cIF3wOLbkusRes0Fh3d887PXhkXstdzMicm4YO8hinFOv9tm51p5zlIiUfEstzIab+ylrnM1E7bDIJZQEVxA6uTCCOYbH1fuqvPXoU=,iv:SQOlIVCakdadheoLR+W3R8rwKKjfgJpudxrKpMxck08=,tag:ydK8u1kSTFqW2kwflQwYWA==,type:str]
    pgp:
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ//U+KleGnhUREPqXiMLTGB3DtYePfDdBMzYl4AzQfW+PKk
            3EER53krvNTSg3InjyqmMuEIhzHiA2umP8klff95uDCMCHSnDZMqNj+MtPAQ3+fh
            h+XlnuDkm0Yct26t4MlqglIZkRvwe4ImZLpnLFbAEQtdMS9vBr6/GykeXnF9z1hf
            mG1sTV5TDO57H+crfO8/i70bHzZSPWmS8EKDvoWeHqeGQujmCLd6w82wUxNkiClg
            gRFrp/s7fTQZ30OW8u9cxj8CtqOV1/KMv7juIIjYanuXxLSQTVu7YUlFtxaHiWTA
            tqWtDvQVSclfcOpGTZ20ZkUSMMqo1roczdUkVD2ZlFIwN4cCIK71q6EyXl6BFFBw
            oGGCUgMlyoW0DgWkfydBeLjYaZxz9nj6Qa9UO8N583HRJD6QKc+eRgTZxpTETGcG
            fOVVH/OElsz6MEVXYiHpaofCvYdwBJNDsJZbvQ58A3R6wJU9oBXCd1tvkARl9zxA
            bYZz316YB3BGLtRFAPsli/Tz1uFwj6W7FaFc7IRzO7CKcI03I0aYMWH0TR6lsxZZ
            uL92MrHnRRApeAlxsFJj/RCfpKnGfCN2Mjwq3JJTOo1/NuBymVECzq48xPMIdgTo
            xWzM/dzstL6VULkxw9X1oqVwPyXx6FGKj2EF8fzgP3N6XfQjK3UoJc+Z6gEBpx3S
            XgH0TcNVqvFNFgjpJtBmvEuLFOTs4eU1FkKUfICUXzPKhLCI0Sx5zj0KCJ7+YYjF
            yxi0P0f1wGhDEH5rmaXXF0OwloX1tp2XsHNZ++9AjNkMmfhy9so0nxmD4alRUUU=
            =UWKH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/8CR0G6qxFRTEtRAMhrEoOjv7+GURNMsD9Zhp4ZEF2Ddde
            4GnIgHxmO1y+5WxTB2ShH7y/IcNJfgoVbDWr5WzZt7p/e+VUh6HPn3qobSToi+cC
            skKva1cSkmKfsPzq0KX/h1Epft5jbAf4cjyy9emmBJZImmFVERv0HNbcrtk4GBfr
            1hC/QaPM6Ibw5miJbdCY4LZdF+pvNuCqO+v80+hPN3zY2iSQvA1IBJaD8MCM3g1B
            J1voGyFGi7PZEwlHAkMlGVEGR/xHm2AhQv4XhZI9kfz+lX0scuUc7gvilubwduLW
            XcQIV2Boh5KcYHvQTXJPMba0eeNPgRRgG1XVA7fGHvkTqMZC+RQdpcypg6kFuHhw
            l5bKk7TVht2qvJeBmx9sv5kTJ8Z+abc1O466Xa0N45J4Lkjga1+BxE1a9P0t981I
            3aT+RTUahVtNKaDibUJ7hNi132mSR9uvk/UO+A8EYeU8q0n6bH1hjRxQ/T75vAtx
            GZJzXay1nkZAIEZ839UrYOliHiWOxEp6hgJ4ZrF4KrTCRPbuhXhQNIDHcnskv8qs
            6VVBGY1qzgaiuKYItPicFLPBTLhB4/w+ZVGPefdKV+vBqPob3WuL+az2/LDrqXYu
            6M32mXgZtOpwlIezgs5HMIXxmqjz/jMt/2Fmggqort98XhOXP0ZsYqbqJHkAjd3S
            XgHbtilQNTUqo4JNVRqH5GukfQuBRAH15tzmWw+LEcKfakl5lOnDEESafKXrZabw
            DxrEBow1o6mPMdTIZCFLooDhWQYQkMw4xfecW4Qfhvzlw+A+S1Zus+7NsnguDB8=
            =u/nX
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
