apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-nfs-spitfire-fast-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:4Y0kLwtjaQ+LGM4Ijdmrp11Kt/8mN3CJyxsH+uKeINMrjAevLTB6EclElgrQ4hapAXnCtMD/NsLu2u9BvwKCRzroPiWh2TrHIfeDwI7mRNfpeE/vzbr+kzPwCT2dMRsmal2iPzSd/+cqM5Kr4TwuFihPwZX9AYou482JDlR/nSO8+SktD273CFT07s5VHUsiYzaRfE1hf9LUvTJ1LV1fDf3imnvX0eRYl/LN+g18sR3lpWYzw73spjU6PU6MpfvRsFaaGaQiaFkUmfrhSKZp50X5R9xwsAQFrUwjX1duDPZxeLwoC/kVErss6aOnvwb1cLqful5QWTPodEYmiXxLa07P5YV0+dT0G5jjeN07Row7NI6r6XuGQo2qlnhT6EoWMltDOc6q8ewkhjQKGkjVxnwKl4Y0D5HuRJV6RmcMp9WQszlNmhff6I0OHIukrLJXhwf4dsh/vTrxKYhNRQWy8DAjHYP107vghX8QKMo5eA9H+MlIs7EgznLoG5eMsd0xcX63YyljKPCHOujs6kBfJt5mms+q/Jkp+TP4vLG0wOMYLEIizwLOWhRHYLlHMTd4wgeNNgGjoPpRsWEPd3AMkZGFFEY/j6voIulnSeQwfRVDXBNArS1ezzTeVTzzu/Gn1Wn5GKMSowPOxIWVzIs6VdobohSbJQS/ysa0/7cmLfGXZBnrZvRJwoZClqD4x0foNygtWrJ4kp3RbZFcSEdC6Oo/ArnYwhAAls4O+HT4dS+YSAEqoeOQ5S/BtWMzUTHD+EpLSD00ohaIvgpS8pBPZd4ducPZaQpy9S/N3utX4FXUceEdenpATXrdUs1bIQCVCjZ/rQF5rGdg4NH3tqV93XIwCaULD+V9Y/DZVgB96qi+qPx5dAUcSQQhrfzB2p3hJeY6iu5RZ2c5pW4hq7YHqykoV8Eq7wHK9mjWpIb8TVnSuWtjkPWY61mSKeh841ywEggtcdb/ZGGPV3+/FvTZNMS0c/G6kuiSZbfXgT91F/UxhBXsb9Hi4FQPKaS2raO1da0aLBhslKel/SoTv1I0bg7plzaBnaAgmBOyod+WJLBd3CEoID/4q4hg82z26YFSL+Sjrug4wNsVQjNKMcUekFmH0FSDN1/lQhRYinp+mnK/UU0TRS+DxoGsBzrLmP+AEsHY0aynyi1j1KS1+OqlC6HHXeh+lj38OnuJ7fuvVV36krIgbq/6kr8RdGFjuCcTaiNeXhUN9Y5ndcG5Av+3uNWQGysfTToH7LKcysaxDPoPIyQUoWXLiwvDl9ZOhL1R871dxB70MSDa4zQEd7WzDRDXr0xn8koDsbAmf64hXYeWVnBDdJFPs74XpOxIQE1lcG7QpywR+nTUgEDNtKlo7WwVUmGQupJxLpHg340ZFwbfaDFnV7LEabDV8HJ1+XMJC6lEoknubMYYJsNYvGg+aIjDBtholV8oxlzIoTeXxyhtpk7jcYG5isBCJ08LfoYTWNgK8XkzcYzAUbjl218bGmgQlTficcs7cIpvV25O6nICEIobU6vyT0hlzmpdIgmz/K/mXhSu7EpHijNEgZWrBBsJeOaHgJ14TEx+Xtd3GYnx4Cdk7mtcwcqhgKTtoMBZufAZR1vZ3tImGawCKijpzrG5KHKTs5U/J+zsHupLCtFKQkhUiIrRMs2k1RaaAMZ1PBtFbzumRW1GjopaLEYgWk/up8TSySEEYcT80dptyTlSAn9t6Wsde4dQG4jxZHLaFtqpEB/NerGEbmYc88dRRCidPxBBagQ9wkgNO1g0vTRDuMBrROgpNZfgoxQJAW+/1XBElF4mnP+UI86R7pQlzunVpTDOfKqzet5h+4nEqAeQYEu/DToZtAZAwmSvFy3h7ZrKoPec7NotX13B07YF/7EG9wX4FefFEhV+HrL6fXe8bsad241s0MZOFv+b7zVIo5KEXfo58YAdD/2f4U/0/qTSdpiERfh4b3Wn/tf1tKr08OwmRPYPJiG5wZB+xRFtQHqrTRQK7YVS6PLfw7RHFeotBDEXojKxKZYym+d0vbA4v7GdAe4zuZ6DzIUy3kvxHKz76U7nSPI=,iv:nlaFfCZS6ngfJb19s84xpg2FRfCTW/eRRTVYvilWcjs=,tag:AlUHvGyjuu60ZhacMY0jPg==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T04:39:48Z"
    mac: ENC[AES256_GCM,data:rOVKhyPR7XIcIboL/fFk9RnlfiCPjMESX00Yna6SIDntu+VHy2aM8a6spzImYz80ZqFDgVUGfEiSJfLQc55sJD9C/XiajVqdRDLU6PArYCxNt0aeAI8WRfBaaT0b/CEZo0tIncCVqPIS+4AhAHzhR5dVi7BWzMxgNZWapGO3PC8=,iv:EhmfrVOhcQtJTWtJp3fkJ3MNyNYfLvCLEONQQ1dtTbw=,tag:NqbpdF0GnT/6pXU/s19HGg==,type:str]
    pgp:
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ//U+KleGnhUREPqXiMLTGB3DtYePfDdBMzYl4AzQfW+PKk
            3EER53krvNTSg3InjyqmMuEIhzHiA2umP8klff95uDCMCHSnDZMqNj+MtPAQ3+fh
            h+XlnuDkm0Yct26t4MlqglIZkRvwe4ImZLpnLFbAEQtdMS9vBr6/GykeXnF9z1hf
            mG1sTV5TDO57H+crfO8/i70bHzZSPWmS8EKDvoWeHqeGQujmCLd6w82wUxNkiClg
            gRFrp/s7fTQZ30OW8u9cxj8CtqOV1/KMv7juIIjYanuXxLSQTVu7YUlFtxaHiWTA
            tqWtDvQVSclfcOpGTZ20ZkUSMMqo1roczdUkVD2ZlFIwN4cCIK71q6EyXl6BFFBw
            oGGCUgMlyoW0DgWkfydBeLjYaZxz9nj6Qa9UO8N583HRJD6QKc+eRgTZxpTETGcG
            fOVVH/OElsz6MEVXYiHpaofCvYdwBJNDsJZbvQ58A3R6wJU9oBXCd1tvkARl9zxA
            bYZz316YB3BGLtRFAPsli/Tz1uFwj6W7FaFc7IRzO7CKcI03I0aYMWH0TR6lsxZZ
            uL92MrHnRRApeAlxsFJj/RCfpKnGfCN2Mjwq3JJTOo1/NuBymVECzq48xPMIdgTo
            xWzM/dzstL6VULkxw9X1oqVwPyXx6FGKj2EF8fzgP3N6XfQjK3UoJc+Z6gEBpx3S
            XgH0TcNVqvFNFgjpJtBmvEuLFOTs4eU1FkKUfICUXzPKhLCI0Sx5zj0KCJ7+YYjF
            yxi0P0f1wGhDEH5rmaXXF0OwloX1tp2XsHNZ++9AjNkMmfhy9so0nxmD4alRUUU=
            =UWKH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/8CR0G6qxFRTEtRAMhrEoOjv7+GURNMsD9Zhp4ZEF2Ddde
            4GnIgHxmO1y+5WxTB2ShH7y/IcNJfgoVbDWr5WzZt7p/e+VUh6HPn3qobSToi+cC
            skKva1cSkmKfsPzq0KX/h1Epft5jbAf4cjyy9emmBJZImmFVERv0HNbcrtk4GBfr
            1hC/QaPM6Ibw5miJbdCY4LZdF+pvNuCqO+v80+hPN3zY2iSQvA1IBJaD8MCM3g1B
            J1voGyFGi7PZEwlHAkMlGVEGR/xHm2AhQv4XhZI9kfz+lX0scuUc7gvilubwduLW
            XcQIV2Boh5KcYHvQTXJPMba0eeNPgRRgG1XVA7fGHvkTqMZC+RQdpcypg6kFuHhw
            l5bKk7TVht2qvJeBmx9sv5kTJ8Z+abc1O466Xa0N45J4Lkjga1+BxE1a9P0t981I
            3aT+RTUahVtNKaDibUJ7hNi132mSR9uvk/UO+A8EYeU8q0n6bH1hjRxQ/T75vAtx
            GZJzXay1nkZAIEZ839UrYOliHiWOxEp6hgJ4ZrF4KrTCRPbuhXhQNIDHcnskv8qs
            6VVBGY1qzgaiuKYItPicFLPBTLhB4/w+ZVGPefdKV+vBqPob3WuL+az2/LDrqXYu
            6M32mXgZtOpwlIezgs5HMIXxmqjz/jMt/2Fmggqort98XhOXP0ZsYqbqJHkAjd3S
            XgHbtilQNTUqo4JNVRqH5GukfQuBRAH15tzmWw+LEcKfakl5lOnDEESafKXrZabw
            DxrEBow1o6mPMdTIZCFLooDhWQYQkMw4xfecW4Qfhvzlw+A+S1Zus+7NsnguDB8=
            =u/nX
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
