apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-nfs-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:M3Cl8mKtCUCvsuviVc7EODS3dC4fOK15ghy6ANrMOh38rmcqWxv/p8I5MrPQ5OIlg+oV1txTA1CQ60wGm1cKK/oU4YG1qtNxIEI3R8VMGyJ68eHyYOwCtXkFmdrxjdWHcLAua9h8SkVDXM6WjuG0PsT8+bVIAxdk1QKmyoMvL0BqFqwWkRc8a1YI4TR1bM02hlG02z+GTRskJRlf1PcldCQ+wDJ/6WfjCShi66nEGzeIfF0gF7KkcXvCUf85lcJrlEibvZz3lWxBEgHQwVZoy14z1qLtQK0nn6E754NJRXjdA32cyakVbWfIAUNA7c0tLhviL+4DiFbzlBGvlDpx2vCDJK5JU6AMqW85wEfQ3A9jCuM5ujQHDzRtclyee5oVXxNMM4WPXOcWcDAtWy+OZqBu1OFA5fjEEihgYzDLaGOHAQVZPW0I8gpu+5jsa3SnR5DpdjyX2z8wcyS+lIjQGPCzRGy84i+2qjZvC+jJM0vkgvL6dpB4sCCOTIabfWEusHtMFagUOSDhIGjM8eKrb2mUFjhdzrfkq6Md61AEGrTr+QKLZh3hasnqKva0omIQdlrh+WUCAgXvoI2ZS1BP9m/pO7XGDSdEvbaa4na55iB9SX9hl4DVm3Cr06i1M5m2ATWGXLkDIHSlfIj5VZsf372JxoE8yrQF2sc0QwKKwhS2o120pdxV0VkLa8FiARantN0zqXikZGyiID61DuIEvroj51+2I1nFtazKXUqw8gSPfDwDDVKjXipOooEYkkdUehV1DD5dCmIEWdjVNjfOrFVeAehgW67q7WjVHAvY2XSO7JFiA6BX//Lj6NmIgovXht2XOoiXc5PYURdoSrvhcOoCOpsr2Hrn9idiVoMIgbOakY9hnztYWlkLX6sZiDO1HGnW2OnHvubS2vTewfCbarKiHcgz8qxAIko+krWhgxMccrCMf5rlP88ECj+czyIFYvqrjATj0R/e2kCel9y9N/AHh6rQrFubu281ohdxBXsLAs0TToyYB42ABYOqGjIzY9IKohr4jKzcwh5ZlqlD6VUJZFPbIWptN11La48YDW0IfptQCGND4LVp5WX5YgFdNCKe7myQA9diUXoQIvkGgSuw2l2gwvTHXTZGiJSFykIeCF/cvTn0v484o4YngXWkRiv+YboIcM6bIJ7VGeVVsg/dLueMZj78SzPqy/QBONCfXqwMrnD8pocTyssQPxnAHTLmxtsjr06mYVvzqEP6lnRQ7pfyPFVTxleeeDaxqVAVOF9CEoXW/68SFAOGGIHYttYpEXSuhkzGZ/NL9fJUy5g1DWskr6EcDhfl0CXJltUq28YJWVX1K0Kr7Tr2Nd2tHZeCXMfvA7+kGKoJeSoRhXJV9LBpiy09KLK8aLCWeCESLLJxlcNPoSrJGxkk5z/CvsAA5E/G0TUQkIyuadUjcSeLIQgmy8yjbEm3VV+N8B+QoVigRVMhVMqgkc1cYBlwqfzU/qV+GCULlRu+WIGXKPhZ6OlCoI72w3a/ifwZFo1bwa0MHjvOzt07r3EzVADIe+pioza5f7HNtQnvB3qtC0K12fRZCqc3Sz4LrFOTOvOxd3D+V03Dz/5xHEV26i8zmp8kvbR3zwQdeSgcHaGMBJdGXfi9J10y7ijMkn4lhvSa270xSQiAxMq19oygX3XzP8vOZ7spgc6wnA/JnttyoPOFq26i7gsRfmRigasCDxg0Iu9B/kqtfx1+SLUygl52nZNj5pRsT6pxuqqhuG4NoeIxqasvHi1tf2V4fnd9Af/SiWesoFtqT6ur51S0odwtDv+lAaACHVarr8gSPfQVhtC4kjTVCz3KQCv06e82k87txFNOezbne74W9j9MVjmvzz9cPBR4fBDa2CPFIqCrjZFtLyxDPyqHVszhPkBepxJxNpYpz5QQ64USIsUr7B6tQeQOyTci8KKfc+AFjEB/YJZ21vWnSzQbA6hMOv0cZ+Rfv4iIklRXi1V4cnc7uL+K2PioHbwdeYo+7CRNumlHFAxVNw3rTOX+fibXIR7foUiW+mz1xUqgLyl7HIVcJLeivWc=,iv:H1IZegp650ISG+pobltABgcvEqop2yKkTEhCuW71EUg=,tag:Pi5OMKeBoz4yUWXxokAsRQ==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T04:49:53Z"
    mac: ENC[AES256_GCM,data:k9JmO6K0NG6FqfiBVjEreFhfoWzqltU1CgKjwOmVhypb1X36AjK0S/Td/yt86GvsW4zBQidABFtVVNJWpsYGEnFPnI2TL0OjRM9j2tqL5JM/8Hk2UYf03gew1/gnQxOOSaUkxmkToxzzNqXwxMLEYkoumPoFByfX5MoHdOPa8Vg=,iv:7kod90/xSNteqbCiMnZAhSiowqB74BLZ7pggioSJ5Nc=,tag:RkH5SrnBz+ZOv5vtlmZsDA==,type:str]
    pgp:
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ//U+KleGnhUREPqXiMLTGB3DtYePfDdBMzYl4AzQfW+PKk
            3EER53krvNTSg3InjyqmMuEIhzHiA2umP8klff95uDCMCHSnDZMqNj+MtPAQ3+fh
            h+XlnuDkm0Yct26t4MlqglIZkRvwe4ImZLpnLFbAEQtdMS9vBr6/GykeXnF9z1hf
            mG1sTV5TDO57H+crfO8/i70bHzZSPWmS8EKDvoWeHqeGQujmCLd6w82wUxNkiClg
            gRFrp/s7fTQZ30OW8u9cxj8CtqOV1/KMv7juIIjYanuXxLSQTVu7YUlFtxaHiWTA
            tqWtDvQVSclfcOpGTZ20ZkUSMMqo1roczdUkVD2ZlFIwN4cCIK71q6EyXl6BFFBw
            oGGCUgMlyoW0DgWkfydBeLjYaZxz9nj6Qa9UO8N583HRJD6QKc+eRgTZxpTETGcG
            fOVVH/OElsz6MEVXYiHpaofCvYdwBJNDsJZbvQ58A3R6wJU9oBXCd1tvkARl9zxA
            bYZz316YB3BGLtRFAPsli/Tz1uFwj6W7FaFc7IRzO7CKcI03I0aYMWH0TR6lsxZZ
            uL92MrHnRRApeAlxsFJj/RCfpKnGfCN2Mjwq3JJTOo1/NuBymVECzq48xPMIdgTo
            xWzM/dzstL6VULkxw9X1oqVwPyXx6FGKj2EF8fzgP3N6XfQjK3UoJc+Z6gEBpx3S
            XgH0TcNVqvFNFgjpJtBmvEuLFOTs4eU1FkKUfICUXzPKhLCI0Sx5zj0KCJ7+YYjF
            yxi0P0f1wGhDEH5rmaXXF0OwloX1tp2XsHNZ++9AjNkMmfhy9so0nxmD4alRUUU=
            =UWKH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/8CR0G6qxFRTEtRAMhrEoOjv7+GURNMsD9Zhp4ZEF2Ddde
            4GnIgHxmO1y+5WxTB2ShH7y/IcNJfgoVbDWr5WzZt7p/e+VUh6HPn3qobSToi+cC
            skKva1cSkmKfsPzq0KX/h1Epft5jbAf4cjyy9emmBJZImmFVERv0HNbcrtk4GBfr
            1hC/QaPM6Ibw5miJbdCY4LZdF+pvNuCqO+v80+hPN3zY2iSQvA1IBJaD8MCM3g1B
            J1voGyFGi7PZEwlHAkMlGVEGR/xHm2AhQv4XhZI9kfz+lX0scuUc7gvilubwduLW
            XcQIV2Boh5KcYHvQTXJPMba0eeNPgRRgG1XVA7fGHvkTqMZC+RQdpcypg6kFuHhw
            l5bKk7TVht2qvJeBmx9sv5kTJ8Z+abc1O466Xa0N45J4Lkjga1+BxE1a9P0t981I
            3aT+RTUahVtNKaDibUJ7hNi132mSR9uvk/UO+A8EYeU8q0n6bH1hjRxQ/T75vAtx
            GZJzXay1nkZAIEZ839UrYOliHiWOxEp6hgJ4ZrF4KrTCRPbuhXhQNIDHcnskv8qs
            6VVBGY1qzgaiuKYItPicFLPBTLhB4/w+ZVGPefdKV+vBqPob3WuL+az2/LDrqXYu
            6M32mXgZtOpwlIezgs5HMIXxmqjz/jMt/2Fmggqort98XhOXP0ZsYqbqJHkAjd3S
            XgHbtilQNTUqo4JNVRqH5GukfQuBRAH15tzmWw+LEcKfakl5lOnDEESafKXrZabw
            DxrEBow1o6mPMdTIZCFLooDhWQYQkMw4xfecW4Qfhvzlw+A+S1Zus+7NsnguDB8=
            =u/nX
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
