apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-iscsi-spitfire-fast-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:HpaO39OUQZFo2M1KZAHR66GhE9RJFJYxurp7nvfkHQEblmrbbulxhLQYvTgKX3B7177d8GGZCcp4U8AuIf78VzBlL8iJBn96TUB6TVdhAYllcskonEjqd222GEFwf+xHVALvX1ul0z4RJeF/DpbNcuogcUH9pELESkpvttwkjRD6qH/wWQ/DhpyRJsMF8+hPB0yfHWDU5xXI5A4K7EFZ/XSbmQQVf6hrrtb8oeJqp+4vGPHux/LKdenX6yKuFIquFj4BgGSKZyW838l2hsytjurXUzQRwGY7WgHZz099pBrdzPindioExiu2DkEtfW1snTXTBb+pOA7UbxwgQ1t1i3qawWhD6jsTys2jfbCB4zCMX00ygOQO5WkukzLH2DecBFZ2f9KK3B7W0Kl0k1HnyShDc2M5LMNDkwY2zBuT6rnwOXEDBj7Zg8KtbaosQr1Z1RIesp+nggTZJCjFl/lJozZNZ+BnOa40zQ3Oa9WWXj//+WUuRXn5Gttuiv4okdZi5BXL/QJJRwx0eTD4TbCV8+CGDF77VDgMtG4m1rUIIYTgXkhj3aKZSIXrzJ5DC+j48d2h2qGxMvaC8hGWxrkyhJLpXT5OYImy/lGNZQWRwwxaMAGuRe6zda1EHCQIBtJ4lgIshfVhM3T5zYTXU0yIs8asuLC4pJx52MtTen3+r36UcWCp0S+ek+/8XPHJwC8Tk5JpG6Kyrs2dK90aKthEVjCs5Rs6qOK1IOVOCNn+bFrgq0uxftp3GU5xRuiwlDmLHtpYJcoGAIXpJHSFRIumq9kTwRbnavoNwxUV2D6iGgu2lqlX3Kd7Q7oPk/kyijHtY4d8FB/Thiy0sre6G4FP5xAnPuDJdqAemaFeB+nXmnpzSKYNyxigRNuQMITgBWMTf5166VLeNTVtImCQkrvJLbgG/nu+54VWGz61q2CdHhopjPq6NhlPv9+4irEO/LcdLDQfBgLqETuRCVhR7Rx8lDyz3r/Gp5pqRSTxC8vgwRem/9qBLjAkEf0KKL6/6Wk9aFk4NI78ntjp7SZTuTNlkF7b5/+o+pYbLA8R8ayMZ6JlCnm/850EL8IJEaB5g/OjD6pzXnau7Jn4q4H6hehfbjqtLymikrGcbIVnxPPeizMTMNWYBvtw95qlktZyIdmk+F45IndJXseu4FNX05rksul1HcwlwnwI/YD/mbXzckBvebeY+RjSvRHeZX6g756DAZK2+isTqvymV5FExqY4QKiXca2zpQrlH12SI0Knh0Mi/Jema5bn3MjrXwdXAaU0m3DPC1QPDvMgeWf/hvnvtf0CM31v+4zjlOFjPX9nQeoFY15CJfd86zsU+NyKdRrpTcGeJKL0x/IjSO28flqUbP3de3YypEfb1M3J8zxOjD3EN08kguCYij1IGbBZRlAe6YHF3Wx2oiaZg9cYHZ4yc0bxrJCl/mGWEWywTrwb4d6vVvj2o++y5XxQ1lNIZYaNsTjNxntAAivtqq7fJBdURzUIak4LIaAFZau63Nb5xUZuXzZVAxiEx/T2uRMMw99bEZqxoisV7fifGrmqsam39FG3sVOH4hgnGcscEl7EJWjaO0HaYDXeHndXz/OoV57yULJ2fn5KZCjVmXTaAEF951zl6koKzdvwT1NClA0Rb8dMqfPMPFX6BRuqto/W7NMvgEl5H42F5edYObcBmaTAmW2b1RtlTpKOUGVVhXgs3LxQ6Wo5KM9/UfPfnyryn9DC6kj71TD6X5weRxb6rVIymy507SDOiCUTkTkmFXfo7UpEY6AeeoxUMq7XEa1B+7/eePGmsQ6pJYrfhFs/In6JLWsbWpvDK5ZaV4GFSGWHlrCcxv+kRoRovMZXYh/aWMoVHG01dTezCxpq/62GgS7o06wDxKgiPfAwIvndNeF12aXk1rAtcIgFBtFzXqGLt/V9OhacBW0TPHGa5nI5Pqk5+6HR5eg6eW7IOOq0fOSkCjpzfX+pZp4pAHB9oKpbu/UQL/wrkJ3Um1pahcRA+OPBa92Lcc1UU9DRSenaSqQQ/poMK4sPDEYJXCs1IomPqOzSBoGz68mOLh+/f92WALFN4StWKC7HCD0XKMDPf9FrzDAp0g7CkW7k0n36X7VRbm+pOfh1ZCSLI52yJ9C53a+QujvGFORoAoL6w24dOZWBZfguIOwJ2YXUHjogRzbvInZw40hR5WILsRLYv/YMW/l8cEbav5IeWWoRremqQTGe1Y/Zc/TMKbhqAFQQBlTXBpJukwVDdNlX5ygYsjNCEKwpqYECkv86YbJnonps5Bl53vcjTPm9NvyfLPXvvNn71fujIb2k0ulreUfwA1m3ansBL9jl/8EfRU3c5O+8CATm1SRgLQi/kR0/TvU8JJm/aPi4hkjntnOWD3CD2TCMEU5Azq+lOHWMxJ5pmoXxCKK7AOruoWqPBfs4Zxb7cz5CR59viovzqA8IOybDUX/kc09lAIYdrt99emqJ2YFJhizXflvyY5wErEIizMWnIhNwyVmoMlJ5TrW2pqt3LIIo/5dUGF3GNbts1zTZqqRiIQ98qgNzsh3NhvMHgDGvEk731aU/S9/h2yq7D3OWCVH6cBePY4L0+ojQn5dHBMZupgJxTQA1vcaIT5msDO7obISWq+1zljI3UWG61ujNNUnMXuacaBJMjzMCqqDxiJhUhdMUwcjjIFo0Df0rz8WT2wxwhe4KVcP4Vj0g8X0AZQg6Il5OUv+lUdLr97/ijtnpxoFkZuYNokz/+jPmfk7xoWLIIYwBnUfmhftvNLzHTrJLMVxOX3TI+WkyJ1jtr/ir2M8nr7/W3VViCpSwfEMXoeGQ25IyYSymNE1kkIYePszc0PBzrEZViaFCJ5F6pwLtlWi6Bjr8xG4nZgE1oDkRhA1fMobM/z+ihYkgYpZ92tHjzWI1EuFPiKO6ZO9m/TCg7h5feY3CsGvuwWavdwupkeo64XThLgMG50sVPIJW50IEb4hMZ7VsQpGuOltxyhnEDqA9D7peg+jjSuXPkg7CznAmGdPDF1KkKN0c7ydo729SJhw/E31H7kPfL1U3mdtbFhPux8LFF5wqyl/s9HsXaIDsvuh3GNJCPndvgnaj0vDUSCuUYDRRaeP9mwTzPfEPy2V3LazQ2ZvYRM/Dr+cestLepawp9App6tUJyQGDu5+BUwDftWr7vogsMmMluT7oNKDuuU/5E10Gha5o0JkcEiCBZOHKINtQS2wsxSjb80n5hieieO3Db4BEew/0a7zWgLiHHVAe6jnMRBO1qcWjZ723UbwLZmeo+5ZikRpshmianmyJ1FILNiHAYhNEsMrnuR33NjBG81nrNM/L70mG7v1mrEr9tqj3Wzi6i2WVVHVwnCq3DF0ZwHGvL1DA0iTki5b+Pu/uYyYRO8+/lV/W9dyl,iv:Yg8yEsq9ZpH+ALWrmXt1LvSgZHfRbnaBd+o7eBRh3h0=,tag:3Iao39bEJThvC9+NQr6NrA==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T02:09:02Z"
    mac: ENC[AES256_GCM,data:4Kt9Ucz9U5wo2uIJhsa8Bg5PGnimD1JkLZKN3S1vAImM4BrimR0jsaJcw71JWwROumtoK61Q5ep3c42WqLUGiPK+TFmIbNPt4tMRaB+aULLCL6w7jml0OqIB1LQPJTzaP7U7WgGIpMiD7S1N1yoUMQ1MxQIhNVavMdvorT7Flno=,iv:2uYO5ZCKmKRqEDgLY0gXdYwLsCoOTNX/6a/OyesQFeM=,tag:Xsu7ZR8JR/y9XDwBL5chMw==,type:str]
    pgp:
        - created_at: "2026-02-16T01:09:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYAQ//ZUTLbiEehYW8Id7BAXo94UyEhnaMfKumVoqkBAC8OyHI
            yCxrqhhP+unCf2yO3oFJqncsLVvyqSA4LVYGUe7u0I0BRUwr7sfm63vzL1zJeTo7
            PDeupudMqN3JPVLx4K4bR5XjGyryC+UiOFs++FSg7PMs2Mz5BqMv077Y84kBJX7i
            v55sip5PIDBFLU3NlIMi++jbynrNhtmbrp8kcgMOHSH/sum0p1b3+YTuVoTGAsLa
            ZDwz/Dm8qJx8JL7EaGYjSBWq90LWrS1o7WsLzQ9TFWzwf7K+dTzqmLjum6FkVrBX
            SWdWEogEzBfZSPMKrBDpuE4nsB6l1dcBg6JCUmFLO8Qf0mu71EgMj5p36G0Zs5pl
            gqf1P8TQLSO9y3hBtXSP/ecYAL2D+gUeFutu6hcsSio8HYrFL68ypUWRu9ypYrQ9
            lL+7DzochTovfq+II+L4d8luYIVqEvP0Y0NOYOcKPGsdEo9DCCDAlyNKHAzmf3Xr
            2sWTWO998wLvMr6YG6aC5JTIPBf0MxGOjYRMTVOmHhxDwfEuECmL+9SLi5Nw4bfI
            sXPbAFVi4Xk2CMAbyozLLzQRJzt3m/8GRIiqEWExkDsQi3RBG/xkTSh1oxoGkRIh
            r3ROWqkL90SHqgQLycsttHb37Z6zQDTjHIa+oWOlXQ3x1J4zGGw7n5EdC/DdRNLS
            UQF1x0jm0DDrL4uP0m9V6Ya4gxjoc9FzB+iIPD1upA/A3RaJNEXZtsI7guKxv8Tg
            cSpKeQCeHjcdSFDe5eEcdcR07a7bxHnWUMBQkmFgvRpFkQ==
            =YKv/
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-02-16T01:09:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9AQ//X27qsInVw+ia/2buuupOXVeUhNJYR1gKTuyKwUtKmK/E
            ZbIIrnbHgyPq51N9rUsiaP+a+0PFEuieYogk5eP6y88LK6wXn1vau4Wp9nXWdbF6
            SJWKmMNZwntUqLasiIeX7S7kBxVO17r7LFFx4mg96XeoGkrB0kHp4dpTCopsSUgy
            SUK05W/pCbCxcbgtnV1wtklyH9UuBJ7STVAo1r0cYhBtYNYwh+ZvicVFEAtVdqzV
            1bmBuxu881tgguXyLhy+EAAkYuDfU5abCeph4bzZnYEbAylvThtWC30CSs+KDbVq
            UEWyvjX8EF3LRjyecN+PPwdDKQ5AWsMlEXfcHuk/kfXhP9JeA0HoSxyxnGBnapJ4
            gVRcH0UQNjjlvTAMZrCGjOI589kBvlYBWEi/yhARRoBZ7RqWDtiP5gSn0NBT8yBN
            gecY1k+P0S6ay/F+47C1hE61jAZkRDX2uU09I0YoiamxS04DKodrvmEoH2ohJlpd
            X0IAh+TezxpEFOAkErHfBYyipF89R0Q7qDeH6P2N5uDqKfh1HD2L5ldHNWWs+nNF
            Jx26zAdqs1qVtXsdT3/nZXAu/Db1qcnHdLAchtp9AAJBC+A92yZ6UjcMiFK+dMU3
            QTZ5bRWhdPdZXcdWUBAr1zT+hq0oC4Ld7ajWLQPXPXVGjvhHwIt0JPj8ZoUN+oHS
            UQHYajB0sEPUX+hDg1tUAbGyXrVwYK5XrJMQxg5eYcMZQUZNeHp0WEpg1FARQpHJ
            KODsxgPDZUTw9dQYfrvPZLvVRivVyQipsNUzuWah/JpL4w==
            =WAP0
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
