apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-nfs-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:IeXFIhOOs6ZZhA2cHz6S4O+P4OQiy0I6SZSSIJwYfUBwE05fairXb3wVoxISOFx/ROJhfeX08eZJH3zrkooIqgW+JISk8aqgjv3IbQGUFaFo9VHGxYACuS+eQZNUH5V8YYQAZcdCVkj4hnLy7LhLIb9+Oww367t+GU24idyrLBwZJZNqjYRd/rUsOfEiisazsAtAYXdvl20W+aHP/uRvjArmLvz1GYWKkpH1Kg8O8jLIi0tYUKMWW4ySmKTHlw4hthDU/VQaO590RMBh6RYAZYZErySub5qmkw5peNrxm0gVPoX483Feuq0a8laYTgpTka3v+pxMsWNp6JhUSKhCY71k4MFxY16gqg59zMsMUn68tIcosHY6rMvGxLVeiWhgUHIL7/4H42wHloqEWLO/AqOlPIOlQuHLqO/MXz/fknctjySwLlzEJdaI2qJm0KmtrjfAYA12qD6tvDcjS655Ta2p5kWmiKXsGzk6SSEkGHcvePFv+r8JxDuvt+YCCA1Hwgf9g3ZmMT2oonZpRHKB9JlPpDWw+nynDMx0HYmv6t16RqEOocUWRoJiuzOoHkfKkTUSiPD8ibszUrAalhZW/10YaLCkSLMDLnbyRTu3YqNwgWWKtnAGy5Bl2sbsqqMMBVp7/P97mA2A16ZcA73qn2iBBbklr2WxLGxLd0ZWWmLk6mt94JMMCn+TEC1kvP2Ur/b4mvg5cbkS4n7XGcxQKkDSVTS6Sb/ZQ1K8tFLwU7EgmSx6l9nMpNcHfRvhClz4CaCzco+CLS9S9hByFxuxz6j+uqW0pnFHDOKsHuIort44XypSY3kZHKVPvqK4M8ASc9STzPkOBSUEfk2I5mVfLrFR3rc3N12Kv7yKa/sub4h6htIKjlI3NlgPEXkImc2VKLtiBz5zBOKcWEKBc2rSGQDbYIsVOWdoJiwbC7mlQMDxeOw/Clz5ul1m7FEJYzrCxpsbNtySlpBOJKR5ToEgpzfylP7TXufeGP6QJhjur8Eo8ttFKudYafxIR2EkMrVCzDkYpCE6dSWQ0WUvetVm5wmzGwRZaDvThDVoBHVbhG3GO+i+klWgMj/OA793/S5Lkejaj79OpOF1R43MzqSz9Fpdgy11kF/8siY6zSQFSUInJGpQwMYPTGDHMh5Y0konK0nPaftm6jlHvupNPXyAgsQ93PJanRgRungvcO9VjcLRNzcufaM/IO5KBPQhHW+QKtSZPsj+vpodkJLxRD8VNIMYXlzQOFxUX3NtUbOisAoJlGgRkXhvp+SwI6qmnVlhdG9kjqsYZFwxPKL2zK+b20BaHTiisc7j1TuBtc6raxNvXCPJPUmzr5i65H3XRQmxyub3Z+xDsU3UtTkuFEKZOaWNSryZsx2vYSg5O+WL/8m9xTFbMhqtllbXll+u4fhOXIEIdeFgV3yaov/rm++opfaNxZYtCqu4Su5yFtG/uzIyHG+q49FIm/8ibxpSkNF+60xVtcD5sofzQvf6QV8nl/5bG5Bnh+VDWVZHR4pfMLYTpICyRb2KUzHVfI0ViOqwWH0AkE58hlPSZVXE1Ekak7qyOGeeBA9wpri2ordsnldqrT79qwL3ckYk2IenS9T0I9UrB0AUTiFdibQnI/q3WUlAc4tRGFwDYVdkHbrr4lLLYV5pVlkiI7hq2WTGyR8yErl/CLHlkGVUB0qonTAaq1nlQ0FLWMbAZ0UeNTsPb0vY8JRGujoWh4Wja1YGjl6aRH/CPQj614G5kv18v+8cc7wWv/1JDVBMA6ev7GwSuU0ay3dMd3sr1Gkg8O6yUBfMHx9q7mK3270uVmL0qBpZSdLWZO2TdpTfTRfQcy1U6WFipXb5A3Nx5Hs+1AnXNIJsxmx++xC5KapaVSwp2m44IQTukrVIvO92Not4MXsNGfmP7sIFwOYxvKPPskkadnXu7T90fc4Wef28RRu1fg1YS41jtjQLiN7IoYWtfXs83TX9f1XQbqhbVNDzagcU5mqzVcisPp4/xErz8uIcNh4Ulmm/rr8HHZtUE4TbUWG0p926F1x+xD96FvokFHc5zA==,iv:SPT6LN3z3x8isIlzySDcdDkTQ8kgRC61hhEE4g/x2cU=,tag:YSldQHKr+yPI3YUBhLbQYQ==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T04:39:58Z"
    mac: ENC[AES256_GCM,data:JdswM7QpftDCrN1sr9orjFqwK99RQZVwKZTepzPGpTOuJ0KObNLEMOHYawqJy7KITk1NPgT019v1H2lnZNezidI+MeFFdrrnEm/zudTbL5n5zRFis89yLPTY9zncIWT2I3VQUZ318GqzYGduU50UMiZpO9lnmep+FUuuwkUGYf0=,iv:/HYzFY/ZnrnVpukkuJQwSoHB/j3hUY0vZ6Y2HdrLyJM=,tag:PCnjjeR1jjwna3BJiiNGfg==,type:str]
    pgp:
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ//U+KleGnhUREPqXiMLTGB3DtYePfDdBMzYl4AzQfW+PKk
            3EER53krvNTSg3InjyqmMuEIhzHiA2umP8klff95uDCMCHSnDZMqNj+MtPAQ3+fh
            h+XlnuDkm0Yct26t4MlqglIZkRvwe4ImZLpnLFbAEQtdMS9vBr6/GykeXnF9z1hf
            mG1sTV5TDO57H+crfO8/i70bHzZSPWmS8EKDvoWeHqeGQujmCLd6w82wUxNkiClg
            gRFrp/s7fTQZ30OW8u9cxj8CtqOV1/KMv7juIIjYanuXxLSQTVu7YUlFtxaHiWTA
            tqWtDvQVSclfcOpGTZ20ZkUSMMqo1roczdUkVD2ZlFIwN4cCIK71q6EyXl6BFFBw
            oGGCUgMlyoW0DgWkfydBeLjYaZxz9nj6Qa9UO8N583HRJD6QKc+eRgTZxpTETGcG
            fOVVH/OElsz6MEVXYiHpaofCvYdwBJNDsJZbvQ58A3R6wJU9oBXCd1tvkARl9zxA
            bYZz316YB3BGLtRFAPsli/Tz1uFwj6W7FaFc7IRzO7CKcI03I0aYMWH0TR6lsxZZ
            uL92MrHnRRApeAlxsFJj/RCfpKnGfCN2Mjwq3JJTOo1/NuBymVECzq48xPMIdgTo
            xWzM/dzstL6VULkxw9X1oqVwPyXx6FGKj2EF8fzgP3N6XfQjK3UoJc+Z6gEBpx3S
            XgH0TcNVqvFNFgjpJtBmvEuLFOTs4eU1FkKUfICUXzPKhLCI0Sx5zj0KCJ7+YYjF
            yxi0P0f1wGhDEH5rmaXXF0OwloX1tp2XsHNZ++9AjNkMmfhy9so0nxmD4alRUUU=
            =UWKH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/8CR0G6qxFRTEtRAMhrEoOjv7+GURNMsD9Zhp4ZEF2Ddde
            4GnIgHxmO1y+5WxTB2ShH7y/IcNJfgoVbDWr5WzZt7p/e+VUh6HPn3qobSToi+cC
            skKva1cSkmKfsPzq0KX/h1Epft5jbAf4cjyy9emmBJZImmFVERv0HNbcrtk4GBfr
            1hC/QaPM6Ibw5miJbdCY4LZdF+pvNuCqO+v80+hPN3zY2iSQvA1IBJaD8MCM3g1B
            J1voGyFGi7PZEwlHAkMlGVEGR/xHm2AhQv4XhZI9kfz+lX0scuUc7gvilubwduLW
            XcQIV2Boh5KcYHvQTXJPMba0eeNPgRRgG1XVA7fGHvkTqMZC+RQdpcypg6kFuHhw
            l5bKk7TVht2qvJeBmx9sv5kTJ8Z+abc1O466Xa0N45J4Lkjga1+BxE1a9P0t981I
            3aT+RTUahVtNKaDibUJ7hNi132mSR9uvk/UO+A8EYeU8q0n6bH1hjRxQ/T75vAtx
            GZJzXay1nkZAIEZ839UrYOliHiWOxEp6hgJ4ZrF4KrTCRPbuhXhQNIDHcnskv8qs
            6VVBGY1qzgaiuKYItPicFLPBTLhB4/w+ZVGPefdKV+vBqPob3WuL+az2/LDrqXYu
            6M32mXgZtOpwlIezgs5HMIXxmqjz/jMt/2Fmggqort98XhOXP0ZsYqbqJHkAjd3S
            XgHbtilQNTUqo4JNVRqH5GukfQuBRAH15tzmWw+LEcKfakl5lOnDEESafKXrZabw
            DxrEBow1o6mPMdTIZCFLooDhWQYQkMw4xfecW4Qfhvzlw+A+S1Zus+7NsnguDB8=
            =u/nX
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
