apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: democratic-csi
    name: zfs-iscsi-democratic-csi-driver-config
    namespace: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:e4qM3BTqHrufVBclfotY47RzYqPUyU01NTsnz16nqTYVGGQGNsyE2lVdOngTPJfp7WIKcnxHyLTnEaSuHCL9TsYcIzKSPaDwvMKmhf4Bw7O7PsNi07+F4I5M6iddbvRf88pNw9D2STiJbxhfeDO+f5DkG6PpLtUh/nVCwYKvRCv3TB3TcwGwxBH/8LSjQAFKHGrd6CYwJBl3T67pqrWmXt8gRLFY1gFNRvHR318n6w2qTKJ1eTY9MDihfBilj66eoK0o7kBdDsDqJgkb9rD0hwBDR2Li2lKZ+z6ihrB0wJJ+xzz+sWUhVUwURLGoYANJHewMPUWNsVSUzKP6pzzb/mrdqD/PwULbe1jTNq15f8OxQA3ynZHum5QuLgc8rz4gSRN7dHT/13wPVtWNv+DLUGtehyEd/1g3eteXMoOarrAqKOzAJU+kNTX76UErTEuyrGvN6i9UNlQirVBNIxmuaqSnXMBqNHdBRTEVsaooJhcq7LuFDVK1BDTqZe8jGNV5M7KJRVRIae1W+0Fyo+CJrMhrPKLJhL9MwSsqQgTfRpM502hcLbwJMP2NkHDN734OSJa7r4GmwhS3czySx1pR6LCeOnIUflFfr72t1tdTtR3oSLY8OoCUTW/MusrjnWjEPpDnnz1pV7t7oVUhEq3fliKi61N/7pBicVL4gxnIE78Lk2LGLoFCk3Wm+gw6XZ34O6PX0OAh6BuO/8d0lES/F7y69pb6zeU5ZYQUBJksKgw+YIhXMEiwo/akCV6+6Gcb3gmAHUEd22RS/uM2pVF/bYqEams8o8iLJEXHluKEMQdCdNYOjVB2JdYlJ++7h03IpGda3AONrNcQng8HiRAnYAG/gH98dCdG+1AbMIICFoX8XwHuPaG1y5/JqKEk+ogYSNzC/vI8kV6ivxYygL7dF3c6fwDhbkjQeDofHdDxWe7XytQN0DF+aEJXu5vk0DRiszVQhZFZH1FiVBN2P3c6BeU96wkEWaD1gAHeVaCFNbHOTqZWATwOeD9d+i0dr4GZ+xkn6aEEfZ4+6lqEaYsK6uVWI+um9ke58pQU/dKy8F7gqA9+YzaE5X94qGwBywXVQRYQm4BS6edZ+Y9TfjmXqh+Z7fpTDjrTW+iJRzWX8kDTcYCxc2mRYj6kmfiyqql4TCD6dmRMWX8xb6/4qUMBmY9BqFV1pnhLCSic8gdU3wBAOzRVFNjkCK8un2lN7E3kjbLZy6vsqkYxWH0WdkRaLZRW9h7jLu236yqN9L7MDM5r/h7Hw84XTDFCggGeNu1NuWueVSKiFes138VjzLulM++XYworNVJhcGR4xEZwYOysd1F2bj5v/WWRYIzVUd2yFv6LkMW4EMQUxvflcNTNiBBtXnAHkch/l5V8WED6Ek0Mw7q3ICEoIu2sznLvLxxe6EcSWHie03Tdo/D/OnOE8+ayRzocjROWL4ae+YrNB1WGX1cM/2N/xFAe20ol1Le/G8rM0YtN6jkt2Ne9k9xH1OpqXWuwupfrafr+qNqisdt+2QBhWNcNd1KVRQdD1Pxo7V7POVoqRwygarAQLaSsjUO4aMuP7CncCGPXfBYnMs6qsTP7H6Dpu+sHQiiex5dN7zsnkcNWVE+NYNCMTn4sh/hKu4zCZeIORkSFdQ7Zc7yukMFf9Z5SV4eLJlCn6mfMTpkIxd4cfADAT6rx3wK7aGPr+rk2QE+XIOSiqcemWh3JEgAxw12Nu9j4EXijAO/cxdgSkmk/7mtNZiLFw3sQ/AfKuTzyoRmyfPLZwxqdLkF0zsvv2yfp7x8MTNAtr4wEMkN8WrMjW0UqleAaHM+JG/kKxmYc5nxqUJDpl6Bg3JapDC20zrIBO2GnqAQkM743nBgw7zg3PZGbLkgEqZji3z2nrYaNkTvgFdS25w4hv58ULiRxfUwNWS8crnAvXo9O6faiLQs6I/WpryoJ8w5Whh1D/ibBBINbW1mw2k5vg+HeWvBZ5dQjlzLZzQti8Ubi/Mdv6b7Z57uKrhOE/6EsvCsblq7Ztr3bjNK2nEtTmAFPmPMaBdQYtstFry705cG717VuDD8fIcnpmbKbHGzYr4RYYAsafh9p51Haqy1P09eLsDpwiWv/m7+djVENQorhO1iweaVsI5Em3i9vpI6W8HKJN86Tm07D7vuw+wrFbNXIaceXB/Y1+rMa07d3oyPA3XCPb5S+9AlgMdgdQlZ9wMj573dVpfmdcp8WypfINiwpi/c5LN+V47HpUVJBqeiIUboyErKBohOF77oUpgp/EZgkB3M4RJ2wFjRnipT4+e8W6cVcK7p308jYaAFDqCMBmpSywhd28FNj61NTA4kfzuocHm2h2i9+5Q880r17pGX8xEasCHY2TLT5YKwtI9smcz7kz6DDf9uvSIs+bKB13HcPwQ+yf0veeIBCZwqMvpB/KkOYQSLjG7ym5+jqM6lxXEa4NhM4V0j1yIvYksgkWPlChE9ftPhkB9uTEWnqa6vyF57BhKk8gRthcMn1yDsmoGqx3oBPcSnwOhKPsqPMRslBhVQHM2GmzqfqqA6rri/pBCb8Rp9jQailD4OT1e0edQHnyEKEUNGz140ASIp+XNoSaY0UPCXxClHFVwTfjBEnx8fHuABJ67mVjDlcqcd6DgcS4k2Rs9oYWoVTpL15O/dITQ1JpwHICgpIitNueW+l9ouoF3nDn3CjsbSntrs9vFwE6T8iJfXZtoxcH3qSKLa8RLNcb+EfUak0PPmYesoBgR31Vlb/ewW/2HVv8Ktbw9QWptlE6YIG+/UMmt9eCJELp9JbYw+PBiWbHIfP8ZzLfCbHYDslnQ/hOg3lKesH/97qkfNyvZ2TVVnxKAY9jew3/ko5suCcLYbRqjdFyGZUV496bP654Gs+g8lGdMb+flBOMgQWqtR6FR1k4LlVZWM/BPdmyLW6Dlhd1VZ9c93pH0dnNaDf5w934apXhVE1bJb86WwxUNeafqpwMjOOdRKbPXR5IrN1Uqg619okISgKmKhMRZ5gr5Zjz7N4nTUa0MaOubrVu5v2M1rET+49HJyidi2foIC3o79VFy2yhHwY8nKIIYk29FVTBaBK6YXGq9Wo3l+XWrrp/W5NEdz/lF7DtnNuS7qXggWML/cZiHLcet+KizQi/HklLVkVpHj9GnXwlNs1h7fSBpsC0F3EdowUpLRXYsrTk2gX/ZCnk6f1WBL++p2C3c4bq5BxZs/mI0ig/YMO4Q2uD1gcAHqMxF2KeqQKR4w+FjeU0nadceobf4U1ntrObZY+Gr8UcEDgYvK5fWVT5BGS512+NX6u8rSRqc1P63uplnLcylpAZf6rJtLXkmzbgGIFlvo0RjpQsO8DF1xbh21Bxocuo1huQQrQOb3rFi8zk9K9I3vfvqESOC0=,iv:4CirgwGM1ogW8kU+uzpd12w7vyjXe6Sycqn8kPIe+Ps=,tag:KpAuI52ezYih217kGN+qyw==,type:str]
type: Opaque
sops:
    lastmodified: "2026-02-16T04:49:39Z"
    mac: ENC[AES256_GCM,data:h+qqvFPQL0lrIQt1W2Sc246Qcyoso0j50h9BYqPv3kisHJUPa4QevkeKuphslD81Rv1Y89+ioJSr386J1T8hwtHLd01/949N3jJ4dhZ7u5D+0xeq3A1F6GS4VPEW2xyLiptEGcFPiaqPCTQHPXXQ9hxfCMv6lP/rbGL3WpHnO8I=,iv:l2smFigvSKY0u5hSQ6O8OPfrJlw+Fmlv9Uyizzjt0BE=,tag:ljvfuc+kbAV5GWOEYTb/Yw==,type:str]
    pgp:
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ//U+KleGnhUREPqXiMLTGB3DtYePfDdBMzYl4AzQfW+PKk
            3EER53krvNTSg3InjyqmMuEIhzHiA2umP8klff95uDCMCHSnDZMqNj+MtPAQ3+fh
            h+XlnuDkm0Yct26t4MlqglIZkRvwe4ImZLpnLFbAEQtdMS9vBr6/GykeXnF9z1hf
            mG1sTV5TDO57H+crfO8/i70bHzZSPWmS8EKDvoWeHqeGQujmCLd6w82wUxNkiClg
            gRFrp/s7fTQZ30OW8u9cxj8CtqOV1/KMv7juIIjYanuXxLSQTVu7YUlFtxaHiWTA
            tqWtDvQVSclfcOpGTZ20ZkUSMMqo1roczdUkVD2ZlFIwN4cCIK71q6EyXl6BFFBw
            oGGCUgMlyoW0DgWkfydBeLjYaZxz9nj6Qa9UO8N583HRJD6QKc+eRgTZxpTETGcG
            fOVVH/OElsz6MEVXYiHpaofCvYdwBJNDsJZbvQ58A3R6wJU9oBXCd1tvkARl9zxA
            bYZz316YB3BGLtRFAPsli/Tz1uFwj6W7FaFc7IRzO7CKcI03I0aYMWH0TR6lsxZZ
            uL92MrHnRRApeAlxsFJj/RCfpKnGfCN2Mjwq3JJTOo1/NuBymVECzq48xPMIdgTo
            xWzM/dzstL6VULkxw9X1oqVwPyXx6FGKj2EF8fzgP3N6XfQjK3UoJc+Z6gEBpx3S
            XgH0TcNVqvFNFgjpJtBmvEuLFOTs4eU1FkKUfICUXzPKhLCI0Sx5zj0KCJ7+YYjF
            yxi0P0f1wGhDEH5rmaXXF0OwloX1tp2XsHNZ++9AjNkMmfhy9so0nxmD4alRUUU=
            =UWKH
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2021-03-15T00:35:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/8CR0G6qxFRTEtRAMhrEoOjv7+GURNMsD9Zhp4ZEF2Ddde
            4GnIgHxmO1y+5WxTB2ShH7y/IcNJfgoVbDWr5WzZt7p/e+VUh6HPn3qobSToi+cC
            skKva1cSkmKfsPzq0KX/h1Epft5jbAf4cjyy9emmBJZImmFVERv0HNbcrtk4GBfr
            1hC/QaPM6Ibw5miJbdCY4LZdF+pvNuCqO+v80+hPN3zY2iSQvA1IBJaD8MCM3g1B
            J1voGyFGi7PZEwlHAkMlGVEGR/xHm2AhQv4XhZI9kfz+lX0scuUc7gvilubwduLW
            XcQIV2Boh5KcYHvQTXJPMba0eeNPgRRgG1XVA7fGHvkTqMZC+RQdpcypg6kFuHhw
            l5bKk7TVht2qvJeBmx9sv5kTJ8Z+abc1O466Xa0N45J4Lkjga1+BxE1a9P0t981I
            3aT+RTUahVtNKaDibUJ7hNi132mSR9uvk/UO+A8EYeU8q0n6bH1hjRxQ/T75vAtx
            GZJzXay1nkZAIEZ839UrYOliHiWOxEp6hgJ4ZrF4KrTCRPbuhXhQNIDHcnskv8qs
            6VVBGY1qzgaiuKYItPicFLPBTLhB4/w+ZVGPefdKV+vBqPob3WuL+az2/LDrqXYu
            6M32mXgZtOpwlIezgs5HMIXxmqjz/jMt/2Fmggqort98XhOXP0ZsYqbqJHkAjd3S
            XgHbtilQNTUqo4JNVRqH5GukfQuBRAH15tzmWw+LEcKfakl5lOnDEESafKXrZabw
            DxrEBow1o6mPMdTIZCFLooDhWQYQkMw4xfecW4Qfhvzlw+A+S1Zus+7NsnguDB8=
            =u/nX
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
