---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-extra
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  claimRef:
    name: immich-library-extra
    namespace: immich
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/spitfire/media/extra
    server: spitfire.storage.235.tdude.co
    readOnly: true
  mountOptions:
  - vers=3
  capacity:
    storage: 8Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-extra
  labels:
    app.kubernetes.io/name: immich
spec:
  storageClassName: ""
  accessModes:
  - "ReadOnlyMany"
  resources:
    requests:
      storage: "8Ti"
