apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: external-dns

images:
- name: registry.k8s.io/external-dns/external-dns
  # My fork with SRV records fixed for cloudflare
  newName: docker.io/starcraft66/external-dns
  newTag: srv-fix-v9

patches:
- path: ./patches/dns-ownership.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1