---
apiVersion: v1
kind: Service
metadata:
  name: wizarrr
  labels:
    app.kubernetes.io/name: wizarrr
spec:
  # wizarr hardcoded an ipv4 listener in their dockerfile
  # https://github.com/wizarrrr/wizarr/blob/main/Dockerfile#L108
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  ports:
  - name: http
    protocol: TCP
    targetPort: http
    port: 80
  selector:
    app.kubernetes.io/name: wizarrr
  type: ClusterIP
