apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarrr-config
  labels:
    app.kubernetes.io/name: wizarrr
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
