---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-plex-config
  labels:
    app.kubernetes.io/name: kube-plex
spec:
  accessModes:
  - "ReadWriteOnce"
  storageClassName: truenas-iscsi-spitfire-fast
  resources:
    requests:
      storage: "20Gi"
